"""Build RELEASE_REVIEW.md -- the committed reviewer contract for the release candidate.

- Teleology: a skeptical external reviewer must be able to answer, from the
  artifact alone, what exact claim is being made, what artifact subjects the
  claim binds to, what command exercises it, what must agree, what evidence is
  digest-bound, how to read a failure, and what the verifier cannot prove --
  without trusting prose and without becoming an insider first.
- Guarantee: --write renders RELEASE_REVIEW.md (repo root) and
  receipts/code_lens/release_review_contract.json from the SAME sources the
  release-candidate proof enforces -- the committed demonstration's hero row
  (the expectation policy), the proof module's contexts/filenames/failure
  taxonomy/boundary constants, and SHA-256 digests of the committed artifact
  subjects; --check regenerates in memory and exits 1 on any byte drift, so a
  reviewer contract that stops matching what the proof actually checks goes
  red in the gate instead of rotting into prose.
- Fails: SystemExit(2) when the committed demonstration or an artifact subject
  is missing/unloadable; SystemExit(3) when a rendered surface trips a
  secret / private-path / atom-bullet / public-entry-overclaim guard;
  SystemExit(1) from --check on drift.
- Reads: receipts/code_lens/first_action_demo.json, FIRST_ACTION.md, and the
  release_candidate_proof constants under the substrate root.
- Writes: RELEASE_REVIEW.md and receipts/code_lens/release_review_contract.json
  (--write only).
- Non-goal: grants nothing -- the contract documents the proof's claim and its
  refusal taxonomy; it does not authorize release, assert external
  attestation, or widen any claim beyond the distribution-true encounter.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from microcosm_core import comprehension as C
from microcosm_core.release_candidate_proof import (
    CARD_FILENAME,
    COMMITTED_DEMO_RECEIPT_REL,
    CONTEXT_IDS,
    EXPECTATION_EVIDENCE_REF,
    EXTERNAL_SIGNATURE_STATUS,
    FAILURE_INTERPRETATIONS,
    PACKET_FILENAME,
    PROOF_BOUNDARY,
    REVIEW_DOC_REL,
    VERIFICATION_FILENAME,
    derive_context_encounter,
    extract_committed_expectation,
)
from microcosm_core.release_candidate_proof import (
    SCHEMA_VERSION as PACKET_SCHEMA_VERSION,
)
from microcosm_core.skeptic_flight_recorder import (
    FIRST_ACTION_HERO_GOAL,
    sha256_file,
)
from microcosm_core.validators.public_entry_docs import (
    PUBLIC_ENTRY_OVERCLAIM_PATTERNS,
)

CONTRACT_SCHEMA = "microcosm_release_review_contract_v1"
DOC_REL = REVIEW_DOC_REL
RECEIPT_REL = "receipts/code_lens/release_review_contract.json"
REFRESH_COMMAND = "PYTHONPATH=src python3 scripts/build_release_review.py --write"
GENERATED_MARKER = (
    "GENERATED by scripts/build_release_review.py -- do not hand-edit. "
    f"Refresh: {REFRESH_COMMAND}"
)
FIRST_ACTION_DOC_REL = "FIRST_ACTION.md"
# The committed files this contract reviews. Their digests bind the contract
# to the demonstration: edit either subject and the drift gate forces a regen,
# so the contract can never describe a promise the tree no longer makes.
ARTIFACT_SUBJECT_RELS = (FIRST_ACTION_DOC_REL, COMMITTED_DEMO_RECEIPT_REL)
PROOF_OUT_DIR = ".microcosm/release-candidate-proof"

GENERATE_COMMANDS = (
    "make release-candidate-proof",
    f"PYTHONPATH=src python3 scripts/release_candidate_proof.py --root . --out {PROOF_OUT_DIR}",
)
VERIFY_COMMANDS = (
    "make release-candidate-proof-verify",
    f"PYTHONPATH=src python3 scripts/release_candidate_proof.py verify {PROOF_OUT_DIR} --root .",
)
REVIEW_ALIAS_COMMAND = "make release-review"

NONCLAIMS = (
    "not release authorization or publication approval",
    "not a security audit or a secure-artifact claim",
    "not domain correctness of any component's outputs",
    "not whole-system correctness",
    "not agent success beyond the committed first-action assay battery",
    "not externally signed or attested provenance",
    "not equivalence with any private system",
)

INTEGRITY_REQUIREMENTS = (
    "no private absolute path may appear in any written evidence file",
    "no tracked source file may change while the proof runs",
    "provider credential environment keys are never available to proof subprocesses",
    "the fresh-install context must scrub PYTHONPATH and import from the venv, not a shadowing checkout",
    "install and export work trees are removed after evidence copy unless --keep-work is passed",
)

ASSAY_REQUIREMENTS = (
    "the first-action assay exits zero in every context",
    "the assay reports zero source-body leaks",
    "the assay reports itself not degraded",
)


def _encounter_check_names() -> list[str]:
    """The named per-context obligations, derived from the live predicate.

    - Teleology: the contract must list exactly the checks the proof enforces;
      deriving the names from derive_context_encounter (instead of restating
      them) makes the doc drift-gated against the predicate itself.
    - Guarantee: deterministic; includes the committed-demo arm (it applies to
      the checkout and export contexts; fresh_install records it
      not-applicable).
    - Fails: never raises.
    """
    sample = derive_context_encounter(
        context_id=CONTEXT_IDS[0],
        hero_payload=None,
        hero_return_code=None,
        assay_payload=None,
        assay_return_code=None,
        demo_check_return_code=1,
    )
    return sorted(sample["checks"])


def build_contract(root: Path) -> tuple[str, str]:
    """Render (markdown_body, receipt_body) from the live proof sources.

    - Teleology: one deterministic build path shared by --write and --check so
      the drift gate compares exactly what would be written.
    - Guarantee: every expectation value comes from the committed
      demonstration's hero row via the same extractor the proof packet uses;
      every digest is recomputed from the committed bytes; rendering carries
      no timestamps or volatile fields.
    - Fails: SystemExit(2) when the committed demonstration is missing, its
      hero row is absent, or an artifact subject file does not exist.
    """
    demo_path = root / COMMITTED_DEMO_RECEIPT_REL
    try:
        demo_payload = json.loads(demo_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        print(
            f"release review: committed demonstration unreadable: {COMMITTED_DEMO_RECEIPT_REL}",
            file=sys.stderr,
        )
        raise SystemExit(2)
    expectation = extract_committed_expectation(demo_payload)
    if not expectation["committed_demonstration_present"] or not all(
        expectation.get(key)
        for key in (
            "expected_owner_organ_id",
            "expected_command",
            "expected_validator_command",
        )
    ):
        print(
            "release review: committed demonstration carries no complete hero row",
            file=sys.stderr,
        )
        raise SystemExit(2)

    subjects = []
    for rel in ARTIFACT_SUBJECT_RELS:
        path = root / rel
        if not path.is_file():
            print(f"release review: missing artifact subject: {rel}", file=sys.stderr)
            raise SystemExit(2)
        subjects.append(
            {"ref": rel, "sha256": sha256_file(path), "bytes": path.stat().st_size}
        )

    check_names = _encounter_check_names()

    lines: list[str] = []
    lines.append("# Release Review — the reviewer contract")
    lines.append("")
    lines.append(f"<!-- {GENERATED_MARKER} -->")
    lines.append("")
    lines.append(
        "This file is the review contract for the release candidate: the exact "
        "claim under review, the artifact subjects it binds to, the expectation "
        "policy the proof enforces, the commands that exercise it, how to read "
        "a failure, and what verification cannot prove. It is generated from "
        "the same sources the proof itself checks against, and a drift test "
        "fails when this text stops matching them. Its machine-readable twin "
        f"is `{RECEIPT_REL}`."
    )
    lines.append("")

    lines.append("## The claim under review")
    lines.append("")
    lines.append(
        f"For the goal **“{FIRST_ACTION_HERO_GOAL}”**, this artifact "
        "resolves the goal to one complete first-action contract — owner, "
        "runnable command, validator, stop condition, claim ceiling — with "
        "the owner, command, and validator identical in all three "
        f"distribution contexts (`{'`, `'.join(CONTEXT_IDS)}`) and equal to "
        "the committed demonstration this repository ships; the remaining "
        "contract elements are checked for presence, with an all-false "
        "authority ceiling, in every context. That is the whole claim."
    )
    lines.append("")
    lines.append("What is explicitly not claimed:")
    lines.append("")
    for nonclaim in NONCLAIMS:
        lines.append(f"- {nonclaim}")
    lines.append("")

    lines.append("## The artifact under review")
    lines.append("")
    lines.append(
        "You are reviewing whichever distribution of this repository you hold "
        "— a source checkout, a built and installed package, or the standalone "
        "export. The proof exercises all three from a checkout. The claim is "
        "bound to these committed subjects:"
    )
    lines.append("")
    lines.append("| Committed subject | SHA-256 | Bytes |")
    lines.append("|---|---|---|")
    for subject in subjects:
        lines.append(
            f"| `{subject['ref']}` | `{subject['sha256']}` | {subject['bytes']} |"
        )
    lines.append("")
    lines.append(
        "If these digests no longer match the files in your tree, this "
        f"contract is stale for your tree — refresh it with `{REFRESH_COMMAND}` "
        "and review the diff. The proof does not embed a commit hash: the "
        "artifact may arrive as an export without git history, so identity is "
        "carried by these subject digests plus the per-file digests inside the "
        "proof packet. No public release artifact has been published or "
        f"attested yet (`external_signature_status: {EXTERNAL_SIGNATURE_STATUS}`)."
    )
    lines.append("")

    lines.append("## Expectation policy")
    lines.append("")
    lines.append(
        "The committed demonstration is the promise; the proof refuses any "
        "encounter that differs from it. Expected values, verbatim from "
        f"`{COMMITTED_DEMO_RECEIPT_REL}` (copied into every proof packet at "
        f"`{EXPECTATION_EVIDENCE_REF}` and digest-bound there):"
    )
    lines.append("")
    lines.append(f"- Expected owner: `{expectation['expected_owner_organ_id']}`")
    lines.append(f"- Expected first command: `{expectation['expected_command']}`")
    lines.append(
        f"- Expected validator: `{expectation['expected_validator_command']}`"
    )
    lines.append("")
    lines.append(
        "Each context must satisfy every named completeness obligation "
        "(`committed_demo_byte_fresh` applies to the checkout and export; the "
        "fresh install runs from the installed package rather than a "
        "repository tree, so it records that arm as not applicable):"
    )
    lines.append("")
    for name in check_names:
        lines.append(f"- `{name}`")
    lines.append("")
    lines.append(
        "Contract field vocabulary — owner, validator, stop condition, claim "
        "ceiling — is demonstrated with real compiled contracts in "
        f"`{FIRST_ACTION_DOC_REL}`. The assay is the committed scenario "
        "battery `PYTHONPATH=src python3 -m microcosm_core comprehension-assay "
        "--first-action`, run inside each context, and it must satisfy:"
    )
    lines.append("")
    for requirement in ASSAY_REQUIREMENTS:
        lines.append(f"- {requirement}")
    lines.append("")
    lines.append(
        "Agreement is then required twice: the three contexts must select an "
        "identical owner, command, and validator (`cross_context_agreement`), "
        "and that agreed selection must equal the committed expectation above "
        "(`expectation_policy`) — three contexts agreeing with each other on "
        "the wrong product is a named failure, not a pass."
    )
    lines.append("")
    lines.append("Integrity obligations on the run itself:")
    lines.append("")
    for requirement in INTEGRITY_REQUIREMENTS:
        lines.append(f"- {requirement}")
    lines.append("")

    lines.append("## Run the review")
    lines.append("")
    lines.append("```bash")
    lines.append(GENERATE_COMMANDS[0])
    lines.append(VERIFY_COMMANDS[0])
    lines.append("```")
    lines.append("")
    lines.append(
        f"Without make: `{GENERATE_COMMANDS[1]}` then `{VERIFY_COMMANDS[1]}`. "
        f"`{REVIEW_ALIAS_COMMAND}` wraps verification of an existing packet and "
        "prints its card."
    )
    lines.append("")
    lines.append(
        f"The run writes `{PACKET_FILENAME}` (the digest-bound evidence "
        f"packet), `{CARD_FILENAME}` (the human card), and — on verify — "
        f"`{VERIFICATION_FILENAME}` under `{PROOF_OUT_DIR}/`. The review "
        "passes when generation reports status `pass` and verification "
        "reports `packet_valid`. Expect minutes, not seconds: the proof "
        "builds a fresh venv install and a full standalone export. The "
        "packet schema under review is "
        f"`{PACKET_SCHEMA_VERSION}`."
    )
    lines.append("")

    lines.append("## Reading a failure")
    lines.append("")
    lines.append(
        "A red result classifies; it is never a bare “bad repo”. "
        "Generate-side codes name which packet block reads `blocked` (the "
        "generate summary lists them as `blocked_codes`); verify-side codes "
        "appear literally in the verification receipt's `statuses`. Every "
        "named failure, with what it does and does not mean:"
    )
    lines.append("")
    lines.append("| Code | Surface | Means | Does not mean |")
    lines.append("|---|---|---|---|")
    for row in FAILURE_INTERPRETATIONS:
        lines.append(
            "| `{code}` | {surface} | {meaning} | {does_not_mean} |".format(
                code=row["code"],
                surface=row["surface"].replace("_", " "),
                meaning=row["meaning"].replace("|", "\\|"),
                does_not_mean=row["does_not_mean"].replace("|", "\\|"),
            )
        )
    lines.append("")

    lines.append("## What verification proves — and what it cannot")
    lines.append("")
    lines.append(f"The proof boundary, verbatim from the packet: {PROOF_BOUNDARY}.")
    lines.append("")
    lines.append(
        "Verification never reruns the substrate: it re-hashes every "
        "referenced output, re-derives every context encounter, the agreement "
        "block, the expectation policy, and the top-level status from the "
        "digest-bound evidence, and refuses a packet that has silently gained "
        "authority. A reviewer who needs provenance rather than internal "
        "consistency reruns the generator. Nothing here is signed or "
        "externally attested yet."
    )
    lines.append("")
    md_body = "\n".join(lines)

    receipt = {
        "schema_version": CONTRACT_SCHEMA,
        "generated_by": "scripts/build_release_review.py",
        "refresh_command": REFRESH_COMMAND,
        "doc": DOC_REL,
        "packet_schema_version": PACKET_SCHEMA_VERSION,
        "hero_goal": FIRST_ACTION_HERO_GOAL,
        "contexts": list(CONTEXT_IDS),
        "expectation": expectation,
        "encounter_check_names": check_names,
        "assay_requirements": list(ASSAY_REQUIREMENTS),
        "integrity_requirements": list(INTEGRITY_REQUIREMENTS),
        "artifact_subjects": subjects,
        "commands": {
            "generate": list(GENERATE_COMMANDS),
            "verify": list(VERIFY_COMMANDS),
            "review_alias": REVIEW_ALIAS_COMMAND,
        },
        "outputs": {
            "packet": PACKET_FILENAME,
            "human_card": CARD_FILENAME,
            "verification_receipt": VERIFICATION_FILENAME,
            "out_dir": PROOF_OUT_DIR,
        },
        "pass_criteria": {
            "generate_status": "pass",
            "verify_status": "packet_valid",
        },
        "failure_interpretations": [dict(row) for row in FAILURE_INTERPRETATIONS],
        "proof_boundary": PROOF_BOUNDARY,
        "external_signature_status": EXTERNAL_SIGNATURE_STATUS,
        "publication_binding": "publication_artifact_not_yet_bound",
        "nonclaims": list(NONCLAIMS),
    }
    receipt_body = json.dumps(receipt, ensure_ascii=True, indent=2, sort_keys=True) + "\n"
    return md_body, receipt_body


def _guard_scan(md_body: str, receipt_body: str) -> list[str]:
    """Scan both rendered surfaces against the leak and overclaim guards.

    - Teleology: the reviewer contract must obey the membrane it documents --
      no secret shapes, no private host paths, no raw atom bullets, no
      public-entry overclaim constructions.
    - Guarantee: returns the list of tripped guard labels (empty when clean).
    - Fails: never raises.
    """
    tripped: list[str] = []
    joined = md_body + "\n" + receipt_body
    if C._SECRET_SHAPE_RE.search(joined):
        tripped.append("secret_shape")
    if C._PRIVATE_PATH_RE.search(joined):
        tripped.append("private_host_path")
    if any(marker in joined for marker in C._ATOM_BULLET_MARKERS):
        tripped.append("atom_bullet_leak")
    for pattern in PUBLIC_ENTRY_OVERCLAIM_PATTERNS:
        if re.search(pattern, joined, flags=re.IGNORECASE):
            tripped.append(f"overclaim:{pattern}")
    return tripped


def main(argv: list[str] | None = None) -> int:
    """CLI: --write to land the artifacts, --check to drift-gate them.

    - Teleology: one entry point for the owner lane and the test gate.
    - Guarantee: --write lands RELEASE_REVIEW.md + the receipt after a clean
      guard scan; --check exits 1 naming each drifted artifact; exactly one
      mode is required.
    - Fails: SystemExit 1 on drift, 2 on input failure, 3 on guard refusal.
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write the contract doc + receipt")
    mode.add_argument("--check", action="store_true", help="exit 1 when committed artifacts drift")
    parser.add_argument(
        "--root", default=None, help="substrate root override (defaults to the package root)"
    )
    args = parser.parse_args(argv)
    root = Path(args.root).resolve() if args.root else C.default_root()

    md_body, receipt_body = build_contract(root)
    tripped = _guard_scan(md_body, receipt_body)
    if tripped:
        print("release review: guard refusal: " + ", ".join(tripped), file=sys.stderr)
        raise SystemExit(3)

    doc_path = root / DOC_REL
    receipt_path = root / RECEIPT_REL
    if args.check:
        drifted = []
        if (
            not doc_path.exists()
            or doc_path.read_text(encoding="utf-8") != md_body + "\n"
        ):
            drifted.append(DOC_REL)
        if (
            not receipt_path.exists()
            or receipt_path.read_text(encoding="utf-8") != receipt_body
        ):
            drifted.append(RECEIPT_REL)
        if drifted:
            print(
                "release review drift: " + ", ".join(drifted) + f"; refresh: {REFRESH_COMMAND}",
                file=sys.stderr,
            )
            return 1
        print("release review: check pass")
        return 0
    receipt_path.parent.mkdir(parents=True, exist_ok=True)
    doc_path.write_text(md_body + "\n", encoding="utf-8")
    receipt_path.write_text(receipt_body, encoding="utf-8")
    print(f"release review: wrote {DOC_REL} and {RECEIPT_REL}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
