"""
Implements scripts build first action demo for the public Plectis package.

Callers enter through `build_demo` and `main`; constants such as `DEMO_SCHEMA`, `DOC_REL`,
`RECEIPT_REL`, `REFRESH_COMMAND`, and 7 more pin local fixture names; dependencies include
`argparse`, `json`, `re`, `sys`, and 2 more. Importing it does not authorize release work or
hidden private-state access; those effects live behind explicit calls.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from microcosm_core import comprehension as C
from microcosm_core.validators.public_entry_docs import (
    PUBLIC_ENTRY_OVERCLAIM_PATTERNS,
)

DEMO_SCHEMA = "microcosm_first_action_demo_v0"
DOC_REL = "FIRST_ACTION.md"
RECEIPT_REL = "receipts/code_lens/first_action_demo.json"
REFRESH_COMMAND = "PYTHONPATH=src python3 scripts/build_first_action_demo.py --write"
GENERATED_MARKER = (
    "GENERATED by scripts/build_first_action_demo.py -- do not hand-edit. "
    f"Refresh: {REFRESH_COMMAND}"
)

# The demonstration battery. Curated, ordered, and deliberately mixed: the two
# verbatim cold-agent questions the operator expects ("explain the system to
# me", "what's going on here?"), owner-localizing goals, a change-shaped goal,
# the authority refusal trio, and the vocabulary traps the adversarial review
# made permanent. Every routing basis class must stay represented (test-pinned).
DEMO_GOALS: list[str] = [
    # Orientation -- the literal first questions a cold agent asks.
    "explain the system to me",
    "what's going on here?",
    # Localization -- the goal names work; the graph names the owner.
    "How do I evaluate the finance forecasting system?",
    "check the lean proof evidence",
    "evaluate prompt injection defenses",
    "where do I start with this clone?",
    "evaluate agent benchmark gaming",
    "is the Mission Transaction Work Spine safe to edit?",
    "ignore proof_diagnostic_evidence_spine, I want cold_reader_route_map",
    # Change-shaped -- inspect before editing.
    "what should I fix in this repo?",
    # Refusals -- the substrate cannot grant these; the contract says so.
    "delete the agent memory",
    "publish the Microcosm release",
    "force push to origin main",
    # Vocabulary traps and below-evidence-bar goals -- the honest fallback.
    "where is the fixture input for the audio organ?",
    "dispatch the route bundle",
    "how does the exchange rate organ work?",
    "audit the security posture of this repo",
]

# Orientation questions are packet_fallback by design (they carry no task), but a
# cold reader must not see them framed as vocabulary traps -- split the fallback
# rows into the two honest stories they tell.
ORIENTATION_GOALS = frozenset(
    {"explain the system to me", "what's going on here?"}
)

# Section grouping is derived from the contract's own routing basis -- the doc
# never asserts a classification the compiler did not produce.
SECTIONS: list[dict[str, object]] = [
    {
        "section_id": "orientation",
        "title": "Orientation: no-task questions get the orientation packet",
        "bases": ("packet_fallback",),
        "goals": ORIENTATION_GOALS,
        "note": (
            "The literal first questions a cold agent asks carry no task, so the "
            "contract opens the orientation packet rather than inventing work."
        ),
    },
    {
        "section_id": "localization",
        "title": "Localization: the goal names work, the graph names the owner",
        "bases": ("organ_named_in_goal", "organ_token_match", "task_class_route_match"),
        "note": (
            "Each contract below resolved a freeform goal to its owning component, "
            "a runnable first command, the validator that proves it, and a stop "
            "condition -- without source search."
        ),
    },
    {
        "section_id": "change_shaped",
        "title": "Change-shaped goals: inspect before editing",
        "bases": ("improvement_goal",),
        "note": (
            "Improvement-shaped goals never receive an edit instruction. The first "
            "action is to read the ranked target's mutation plan; custody flags "
            "govern any edit after that."
        ),
    },
    {
        "section_id": "refusals",
        "title": "Refusals: actions the substrate cannot grant",
        "bases": ("out_of_scope_authority_boundary",),
        "note": (
            "Destructive and publication goals route to the authority boundary. "
            "The first action is to read that boundary -- never a fixture or "
            "mutation command."
        ),
    },
    {
        "section_id": "honest_fallback",
        "title": "Honest fallbacks: below the evidence bar, the contract says so",
        "bases": ("packet_fallback",),
        "note": (
            "These goals contain house vocabulary ('fixture', 'dispatch', "
            "'exchange') that naive substring routing would misread as "
            "fix/patch/change intents, or they match too weakly to name an "
            "owner. The contract falls back and says no route matched -- it "
            "does not guess."
        ),
    },
]

_RECEIPT_REF_CAP = 3
_WHY_CHAR_CAP = 220

# The example contract rendered in full (whitelisted fields) in the doc body.
FULL_EXAMPLE_GOAL = "How do I evaluate the finance forecasting system?"


def _contract_surface(contract: dict) -> dict:
    """
    Serialize the local value into the scripts build first action demo payload shape.

    The returned mapping uses the key names consumed by downstream receipts, cards, or
    tests.
    """
    action = contract.get("first_action") or {}
    proof = contract.get("proof_path") or {}
    boundary = contract.get("reading_boundary") or {}
    receipts = [str(r) for r in (action.get("committed_receipts") or [])]
    proof_refs = [str(r) for r in (proof.get("receipt_refs") or [])]
    provenance = [
        {"path": p.get("path"), "exists_in_clone": p.get("exists_in_clone")}
        for p in (proof.get("provenance_receipts") or [])
        if isinstance(p, dict)
    ]
    why = str(action.get("why") or "")
    if len(why) > _WHY_CHAR_CAP:
        why = why[: _WHY_CHAR_CAP - 3].rstrip() + "..."
    routing = contract.get("routing") or {}
    routing_note = None
    if routing.get("basis") == "packet_fallback":
        # The honest-fallback story must be visible IN the projected contract,
        # not only asserted in section prose: carry the compiler's own
        # no-route-matched sentence.
        routing_note = (contract.get("summary") or {}).get("what_this_is")
    clean_run = action.get("clean_run") or {}
    return {
        "goal": contract.get("goal"),
        "found": contract.get("found"),
        "routing": contract.get("routing"),
        "routing_note": routing_note,
        "out_of_scope_note": contract.get("out_of_scope_note"),
        "first_action": {
            "action_kind": action.get("action_kind"),
            "command": action.get("command"),
            "why": why or None,
            "committed_receipts": receipts[:_RECEIPT_REF_CAP],
            "committed_receipts_more": max(0, len(receipts) - _RECEIPT_REF_CAP),
            "writes_outputs_under": action.get("writes_outputs_under"),
            "clean_run": (
                {
                    "command": clean_run.get("command"),
                    "writes_outputs_under": clean_run.get("writes_outputs_under"),
                    # The note is fixed compiler text, not a volatile field; it
                    # is exactly what disambiguates the two near-identical
                    # commands for a cold reader of the hero JSON.
                    "note": clean_run.get("note"),
                }
                if clean_run.get("command")
                else None
            ),
        },
        "owner": contract.get("owner"),
        "proof_path": {
            "runnable_validator": proof.get("runnable_validator"),
            # The short canonical validator form: the release-candidate proof's
            # expectation policy compares live encounters against exactly this
            # committed value, so the surface must carry it verbatim.
            "validator_command": proof.get("validator_command"),
            "validation_commands": list(proof.get("validation_commands") or []),
            "receipt_refs": proof_refs[:_RECEIPT_REF_CAP],
            "receipt_refs_more": max(0, len(proof_refs) - _RECEIPT_REF_CAP),
            "provenance_receipts": provenance[:2],
            "note": proof.get("note"),
        },
        "reading_boundary": {
            "stop_condition": boundary.get("stop_condition"),
            "allowed_scope": boundary.get("allowed_scope"),
            "fallback_guidance": boundary.get("fallback_guidance"),
            "source": boundary.get("source"),
        },
        "do_not_claim": contract.get("do_not_claim"),
        "do_not_edit": contract.get("do_not_edit"),
    }


def _owner_label(surface: dict) -> str:
    """
    Compute owner label from `surface`.

    Inputs are `surface`; notable helpers are `get`.
    """
    owner = surface.get("owner") or {}
    return str(owner.get("organ_id") or owner.get("scope") or "-")


def _basis_label(surface: dict) -> str:
    """
    Return basis label for the scripts build first action demo flow.

    Inputs are `surface`; notable helpers are `get`.
    """
    routing = surface.get("routing") or {}
    basis = str(routing.get("basis") or "-")
    qualifier = routing.get("task_class") or routing.get("organ_id")
    return f"{basis} ({qualifier})" if qualifier else basis


def _table_basis(surface: dict) -> str:
    """
    Render the routing basis as an at-a-glance table cell.

    The qualifier is dropped when it only repeats the organ the Owner column already
    names in the same row; task-class qualifiers, which name something no other column
    carries, are kept. The full label stays in the per-goal block below.
    """
    routing = surface.get("routing") or {}
    basis = str(routing.get("basis") or "-")
    qualifier = routing.get("task_class") or routing.get("organ_id")
    owner_id = (surface.get("owner") or {}).get("organ_id")
    if qualifier and qualifier != owner_id:
        return f"`{basis} ({qualifier})`"
    return f"`{basis}`"


def _table_owner(surface: dict) -> str:
    """
    Render the owner as an at-a-glance table cell.

    Organ ids run past fifty characters with no break opportunity, and a table column
    floored by one of those reserves half the rendered page width, so the atlas display
    name -- which wraps -- is what the table carries. The exact organ id stays in the
    per-goal block below and in the receipt.
    """
    owner = surface.get("owner") or {}
    display = str(owner.get("display_name") or "").strip()
    return display if display else f"`{_owner_label(surface)}`"


def _goal_block(surface: dict) -> list[str]:
    """
    Compute goal block from `surface`.

    Inputs are `surface`; notable helpers are `append`, `get`, `startswith`, `_basis_label`,
    and 3 more.
    """
    action = surface.get("first_action") or {}
    proof = surface.get("proof_path") or {}
    boundary = surface.get("reading_boundary") or {}
    edit = surface.get("do_not_edit") or {}
    lines = [f"**“{surface.get('goal')}”**", ""]
    lines.append(f"- resolved via: `{_basis_label(surface)}` -> owner `{_owner_label(surface)}`")
    if surface.get("routing_note"):
        lines.append(f"- routing note: {surface['routing_note']}")
    if surface.get("out_of_scope_note"):
        lines.append(f"- boundary: {surface['out_of_scope_note']}")
    if action.get("command"):
        lines.append(f"- run: `{action['command']}`")
    if action.get("why"):
        lines.append(f"- why: {action['why']}")
    validator = proof.get("runnable_validator")
    if validator:
        lines.append(f"- prove: `{validator}`")
    for extra in proof.get("validation_commands") or []:
        lines.append(f"- prove: `{extra}`")
    refs = proof.get("receipt_refs") or action.get("committed_receipts") or []
    if refs:
        more = proof.get("receipt_refs_more") or 0
        suffix = f" (+{more} more)" if more else ""
        lines.append(
            "- committed evidence (prior runs): "
            + ", ".join(f"`{r}`" for r in refs)
            + suffix
        )
    out_dir = str(action.get("writes_outputs_under") or "")
    clean_run = action.get("clean_run") or {}
    if out_dir:
        lines.append(f"- fresh outputs land under: `{out_dir}`")
        if not out_dir.startswith((".microcosm", "/tmp")):
            # A first action must not silently dirty a cold clone: rerunning
            # into a committed receipt directory overwrites tracked evidence.
            # Only promise the variant when the contract actually carries it.
            if clean_run.get("command"):
                lines.append(
                    "- footprint: rerunning writes into committed receipt paths -- "
                    "expect git drift against the prior-run evidence; the "
                    "no-footprint variant below leaves the clone clean."
                )
            else:
                lines.append(
                    "- footprint: rerunning writes into committed receipt paths -- "
                    "expect git drift against the prior-run evidence; for a "
                    "no-footprint probe, redirect `--out` to `.microcosm/` or `/tmp`."
                )
    if clean_run.get("command"):
        lines.append(
            f"- no-footprint run: `{clean_run['command']}` "
            f"(outputs under `{clean_run.get('writes_outputs_under')}`)"
        )
    stop = boundary.get("stop_condition") or boundary.get("fallback_guidance")
    if stop:
        lines.append(f"- stop: {stop}")
    claim_ceiling = str(surface.get("do_not_claim") or "")
    if claim_ceiling:
        if len(claim_ceiling) > _WHY_CHAR_CAP:
            claim_ceiling = claim_ceiling[: _WHY_CHAR_CAP - 3].rstrip() + "..."
        lines.append(f"- do not claim: {claim_ceiling}")
    note = str(edit.get("note") or "")
    if edit.get("paths"):
        lines.append(
            "- do not edit: " + ", ".join(f"`{p}`" for p in edit["paths"]) + f" -- {note}"
        )
    lines.append("")
    return lines


def build_demo(root: Path) -> tuple[str, str]:
    """
    Produce the build demo value used by `scripts.build_first_action_demo`.

    Inputs are `root`; notable helpers are `next`, `append`, `join`, `load_inputs`, and 13
    more; invalid cases raise from the explicit checks in the body.
    """
    try:
        bundle = C.load_inputs(root)
    except OSError as exc:  # pragma: no cover - disk-level failure
        raise SystemExit(2) from exc
    if not bundle.get("join_index_present"):
        print("first-action demo: join index missing under root", file=sys.stderr)
        raise SystemExit(2)

    surfaces = [
        _contract_surface(C.compile_first_action(bundle, root, goal))
        for goal in DEMO_GOALS
    ]
    by_section: dict[str, list[dict]] = {str(s["section_id"]): [] for s in SECTIONS}
    unsectioned: list[dict] = []
    for surface in surfaces:
        basis = str((surface.get("routing") or {}).get("basis") or "")
        goal = str(surface.get("goal") or "")
        for section in SECTIONS:
            goal_filter = section.get("goals")
            if basis in section["bases"] and (  # type: ignore[operator]
                goal_filter is None or goal in goal_filter  # type: ignore[operator]
            ):
                by_section[str(section["section_id"])].append(surface)
                break
        else:
            unsectioned.append(surface)

    full_example = next(
        (s for s in surfaces if s.get("goal") == FULL_EXAMPLE_GOAL), surfaces[0]
    )
    organ_count = len((bundle.get("atlas_by_organ") or {}))

    lines: list[str] = []
    lines.append("# First Correct Action")
    lines.append("")
    lines.append(f"<!-- {GENERATED_MARKER} -->")
    lines.append("")
    lines.append(C.public_cross_section_claim(organ_count))
    lines.append("")
    lines.append(
        "This page is the goal-localization layer over that mechanism atlas. It "
        "does not replace the component map or the evidence discipline; it shows "
        "how a cold reader or coding agent turns a concrete goal into the single "
        "bounded component, runner, validator, receipt set, stop condition, and "
        "authority ceiling that should be inspected first."
    )
    lines.append("")
    lines.append(
        "This repository converts a freeform goal into **one safe, runnable first "
        "action** -- the owning component, the exact command, the validator that "
        "proves it, the receipts to compare against, the stop condition, and the "
        "boundary it must not cross. No source search first."
    )
    lines.append("")
    lines.append("Ask with your own goal:")
    lines.append("")
    lines.append("```bash")
    lines.append('PYTHONPATH=src python3 -m microcosm_core comprehend --first-action "<your goal>" --format text')
    lines.append("```")
    lines.append("")
    lines.append(
        "Every contract block and table row below is **compiler output over the "
        "committed comprehension graph, not hand-written examples** (the section "
        "framing sentences are fixed text in the generator): this file is "
        "generated by `scripts/build_first_action_demo.py`, and a drift test "
        "fails if the committed text stops matching what the live compiler "
        "produces."
    )
    lines.append("")

    lines.append("## One contract (stable fields)")
    lines.append("")
    lines.append(f"Goal: “{FULL_EXAMPLE_GOAL}”")
    lines.append("")
    lines.append("```json")
    lines.append(json.dumps(full_example, ensure_ascii=True, indent=2, sort_keys=True))
    lines.append("```")
    lines.append("")
    lines.append(
        "This is the contract's stable projection: volatile fields (timings, "
        "byte budgets, graph tallies) are dropped and receipt lists are capped, "
        "so the committed demonstration only drifts when the contract "
        "meaningfully drifts. The live command returns additional navigation "
        "fields on top of these."
    )
    lines.append("")

    lines.append(f"## The battery at a glance ({len(surfaces)} goals)")
    lines.append("")
    lines.append(
        "Each row names how the goal routed, which component owns it, and the "
        "class of first action the contract produced. The per-section blocks "
        "below carry the owner's component id and every command verbatim in "
        "the cold-runnable source form, as does the receipt."
    )
    lines.append("")
    lines.append("| Goal | Resolved via | Owner | First action |")
    lines.append("|---|---|---|---|")
    for surface in surfaces:
        action = surface.get("first_action") or {}
        lines.append(
            "| {goal} | {basis} | {owner} | `{kind}` |".format(
                goal=str(surface.get("goal") or "").replace("|", "\\|"),
                basis=_table_basis(surface),
                owner=_table_owner(surface),
                kind=str(action.get("action_kind") or "-"),
            )
        )
    lines.append("")

    for section in SECTIONS:
        rows = by_section[str(section["section_id"])]
        if not rows:
            continue
        lines.append(f"## {section['title']}")
        lines.append("")
        lines.append(str(section["note"]))
        lines.append("")
        for surface in rows:
            lines.extend(_goal_block(surface))
    if unsectioned:
        lines.append("## Other routings")
        lines.append("")
        for surface in unsectioned:
            lines.extend(_goal_block(surface))

    lines.append("## Verify it yourself")
    lines.append("")
    lines.append(
        "The routing above is measured, not asserted. The first-action assay "
        "compiles its own fixture battery (which includes the vocabulary traps "
        "and refusals shown here) and exits red on any wrong owner -- the gate "
        "requires 100% selection -- on incomplete contracts, and on a clone "
        "whose join index lacks the comprehension graph. The full battery in "
        "this file, including the orientation rows, is drift-gated by the "
        "builder's `--check`:"
    )
    lines.append("")
    lines.append("```bash")
    lines.append("PYTHONPATH=src python3 -m microcosm_core comprehension-assay --first-action")
    lines.append("PYTHONPATH=src python3 -m microcosm_core comprehension-assay --whole-system")
    lines.append(f"{REFRESH_COMMAND.replace('--write', '--check')}")
    lines.append("```")
    lines.append("")
    lines.append("## What this does not claim")
    lines.append("")
    lines.append(
        "A first-action contract is a navigation surface: it routes and points at "
        "proof. It does not authorize release, source-body export, edits, or any "
        "whole-system correctness claim, and passing its assay is not a statement "
        "about domain quality. Where no route or owner matched, the contract says "
        "so and falls back to orientation instead of guessing. Authority ceiling, "
        "verbatim: every flag in `authority_ceiling` is `false`."
    )
    lines.append("")
    md_body = "\n".join(lines)

    receipt = {
        "schema_version": DEMO_SCHEMA,
        "generated_by": "scripts/build_first_action_demo.py",
        "refresh_command": REFRESH_COMMAND,
        "doc": DOC_REL,
        "goal_count": len(surfaces),
        "sections": [
            {
                "section_id": section["section_id"],
                "title": section["title"],
                "bases": list(section["bases"]),  # type: ignore[arg-type]
                "goal_count": len(by_section[str(section["section_id"])]),
            }
            for section in SECTIONS
        ],
        "contracts": surfaces,
        "authority_ceiling": dict(C.AUTHORITY_CEILING),
        "non_goals": [
            "not release approval",
            "not source-body export",
            "not whole-system correctness",
            "not a routing-quality guarantee beyond the committed assay",
        ],
    }
    receipt_body = json.dumps(receipt, ensure_ascii=True, indent=2, sort_keys=True) + "\n"
    return md_body, receipt_body


def _guard_scan(md_body: str, receipt_body: str) -> list[str]:
    """
    Compute guard scan from `md_body` and `receipt_body`.

    Inputs are `md_body` and `receipt_body`; notable helpers are `search` and `append`.
    """
    tripped: list[str] = []
    joined = md_body + "\n" + receipt_body
    if C._SECRET_SHAPE_RE.search(joined):
        tripped.append("secret_shape")
    if C._PRIVATE_PATH_RE.search(joined):
        tripped.append("private_host_path")
    if any(marker in joined for marker in C._ATOM_BULLET_MARKERS):
        tripped.append("atom_bullet_leak")
    for pattern in PUBLIC_ENTRY_OVERCLAIM_PATTERNS:
        if re.search(pattern, joined, flags=re.IGNORECASE):
            tripped.append(f"overclaim:{pattern}")
    return tripped


def main(argv: list[str] | None = None) -> int:
    """
    Run `scripts.build_first_action_demo` as a command-line entry point.

    The command parses argv, calls this module's builders or validators, and returns the
    status code used by the process wrapper.
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write the demo doc + receipt")
    mode.add_argument("--check", action="store_true", help="exit 1 when committed artifacts drift")
    parser.add_argument(
        "--root", default=None, help="substrate root override (defaults to the package root)"
    )
    args = parser.parse_args(argv)
    root = Path(args.root).resolve() if args.root else C.default_root()

    md_body, receipt_body = build_demo(root)
    tripped = _guard_scan(md_body, receipt_body)
    if tripped:
        print("first-action demo: guard refusal: " + ", ".join(tripped), file=sys.stderr)
        raise SystemExit(3)

    doc_path = root / DOC_REL
    receipt_path = root / RECEIPT_REL
    if args.check:
        drifted = []
        if (
            not doc_path.exists()
            or doc_path.read_text(encoding="utf-8") != md_body + "\n"
        ):
            drifted.append(DOC_REL)
        if (
            not receipt_path.exists()
            or receipt_path.read_text(encoding="utf-8") != receipt_body
        ):
            drifted.append(RECEIPT_REL)
        if drifted:
            print(
                "first-action demo drift: " + ", ".join(drifted) + f"; refresh: {REFRESH_COMMAND}",
                file=sys.stderr,
            )
            return 1
        print("first-action demo: check pass")
        return 0
    receipt_path.parent.mkdir(parents=True, exist_ok=True)
    doc_path.write_text(md_body + "\n", encoding="utf-8")
    receipt_path.write_text(receipt_body, encoding="utf-8")
    print(f"first-action demo: wrote {DOC_REL} and {RECEIPT_REL}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
