"""Generate the release-review guide and JSON contract from the saved demonstration."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from microcosm_core import comprehension as C
from microcosm_core.release_candidate_proof import (
    CARD_FILENAME,
    COMMITTED_DEMO_RECEIPT_REL,
    CONTEXT_IDS,
    EXPECTATION_EVIDENCE_REF,
    EXTERNAL_SIGNATURE_STATUS,
    FAILURE_INTERPRETATIONS,
    PACKET_FILENAME,
    PROOF_BOUNDARY,
    REVIEW_DOC_REL,
    VERIFICATION_FILENAME,
    derive_context_encounter,
    extract_committed_expectation,
)
from microcosm_core.release_candidate_proof import (
    SCHEMA_VERSION as PACKET_SCHEMA_VERSION,
)
from microcosm_core.skeptic_flight_recorder import (
    FIRST_ACTION_HERO_GOAL,
    sha256_file,
)
from microcosm_core.validators.public_entry_docs import (
    PUBLIC_ENTRY_OVERCLAIM_PATTERNS,
)

CONTRACT_SCHEMA = "microcosm_release_review_contract_v1"
DOC_REL = REVIEW_DOC_REL
RECEIPT_REL = "receipts/code_lens/release_review_contract.json"
REFRESH_COMMAND = "PYTHONPATH=src python3 scripts/build_release_review.py --write"
GENERATED_MARKER = (
    "GENERATED by scripts/build_release_review.py -- do not hand-edit. "
    f"Refresh: {REFRESH_COMMAND}"
)
FIRST_ACTION_DOC_REL = "FIRST_ACTION.md"
# Record these files' hashes so --check detects changes to the saved example.
ARTIFACT_SUBJECT_RELS = (FIRST_ACTION_DOC_REL, COMMITTED_DEMO_RECEIPT_REL)
PROOF_OUT_DIR = ".microcosm/release-candidate-proof"

GENERATE_COMMANDS = (
    "make release-candidate-proof",
    f"PYTHONPATH=src python3 scripts/release_candidate_proof.py --root . --out {PROOF_OUT_DIR}",
)
VERIFY_COMMANDS = (
    "make release-candidate-proof-verify",
    f"PYTHONPATH=src python3 scripts/release_candidate_proof.py verify {PROOF_OUT_DIR} --root .",
)
REVIEW_ALIAS_COMMAND = "make release-review"
PUBLIC_SITE_PARITY_COMMAND = "make public-site-parity"

NONCLAIMS = (
    "A passing result does not give you permission to publish a release.",
    "This review does not establish that the package is secure.",
    "It does not establish forecast accuracy or the correctness of another component's output.",
    "It does not establish that every part of Plectis works correctly.",
    "It does not show how an agent will perform outside the supplied scenario tests.",
    "The packet has no external signature proving who recorded the run or when.",
    "Matching results in these three copies do not establish equivalence with a private system.",
)

INTEGRITY_REQUIREMENTS = (
    "scan saved files for the source-root and home-directory strings and the patterns in `FORBIDDEN_OUTPUT_NEEDLES`; a match prevents a passing result",
    "compare source-file hashes before and after the run and record changed, added, and removed files; this detects changes rather than preventing another process from writing",
    "remove environment keys whose names contain a marker in `PROVIDER_ENV_MARKERS`, ignoring case; examples include `OPENAI`, `API_KEY`, and `SECRET`. This name-based filter does not detect credentials stored under other names or in files",
    "remove `PYTHONPATH` for the package-install subprocess so its commands import the installed package",
    "create temporary install and export directories outside the source root, refuse an in-tree work root, and remove those directories after copying the output unless `--keep-work` is passed",
    "replace temporary work locations in saved output and recorded arguments with `<work-dir>`, `<export-out>`, and `<work-root>` before calculating hashes. Do not replace the source-root or home-directory strings: the path scan must still detect them",
)

ASSAY_REQUIREMENTS = (
    "the recorded exit code is zero (using the combined package-smoke exit code in fresh_install, as explained above)",
    "source_body_leaks equals 0 in the scenario-test JSON",
    "degraded is not true in the scenario-test JSON",
)


def _encounter_check_names() -> list[str]:
    """Read the condition names from the same function used by the generator."""
    sample = derive_context_encounter(
        context_id=CONTEXT_IDS[0],
        hero_payload=None,
        hero_return_code=None,
        assay_payload=None,
        assay_return_code=None,
        demo_check_return_code=1,
    )
    return sorted(sample["checks"])


def _surface_heading(surface: str) -> str:
    """
    Return the section heading for one failure-code surface.

    The taxonomy's surface field groups the codes; carrying it as a heading keeps each
    code's meaning and non-meaning in full prose instead of a four-column grid whose
    cells run past two hundred characters.
    """
    phrase = surface.replace("_", " ")
    if phrase == "generate or verify":
        return "Generate-side or verify-side codes"
    return f"{phrase[:1].upper()}{phrase[1:]}-side codes"


def build_contract(root: Path) -> tuple[str, str]:
    """Render the guide and receipt using the saved example and current code."""
    demo_path = root / COMMITTED_DEMO_RECEIPT_REL
    try:
        demo_payload = json.loads(demo_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        print(
            f"release review: committed demonstration unreadable: {COMMITTED_DEMO_RECEIPT_REL}",
            file=sys.stderr,
        )
        raise SystemExit(2)
    expectation = extract_committed_expectation(demo_payload)
    if not expectation["committed_demonstration_present"] or not all(
        expectation.get(key)
        for key in (
            "expected_owner_organ_id",
            "expected_command",
            "expected_validator_command",
        )
    ):
        print(
            "release review: committed demonstration carries no complete hero row",
            file=sys.stderr,
        )
        raise SystemExit(2)

    subjects = []
    for rel in ARTIFACT_SUBJECT_RELS:
        path = root / rel
        if not path.is_file():
            print(f"release review: missing artifact subject: {rel}", file=sys.stderr)
            raise SystemExit(2)
        subjects.append(
            {"ref": rel, "sha256": sha256_file(path), "bytes": path.stat().st_size}
        )

    check_names = _encounter_check_names()

    lines: list[str] = []
    lines.append("# Release review")
    lines.append("")
    lines.append('<a id="release-review--the-reviewer-contract"></a>')
    lines.append("")
    lines.append(f"<!-- {GENERATED_MARKER} -->")
    lines.append("")
    lines.append(
        "Use this guide to compare the component ID and suggested commands "
        "returned for one query in a source checkout, a newly installed "
        "package, and a standalone export. "
        "`make release-review` runs the comparison, saves the command output, "
        "then verifies the saved files. Below are the expected values, the "
        "commands to run, and the meaning of each result."
    )
    lines.append("")

    lines.append("## The claim under review")
    lines.append("")
    lines.append(
        f"For **“{FIRST_ACTION_HERO_GOAL}”**, the three copies should return "
        "the same component ID, suggested command, and validator command as "
        "the saved demonstration. The JSON calls the selected component its "
        "`owner`. Component IDs must match exactly. Command comparisons "
        "normalize whitespace and remove recognized invocation prefixes, "
        "such as `PYTHONPATH=src python3 -m microcosm_core` and `plectis`, "
        "before comparing the remaining command and arguments."
    )
    lines.append("")
    lines.append(
        "The generator runs `plectis comprehend --first-action` and the supplied "
        "`plectis comprehension-assay --first-action` scenario tests. It does not "
        "execute the suggested finance command or validator. The output must "
        "also contain instructions for when to stop and what not to claim; "
        "all permission flags in `authority_ceiling` must be false. Presence "
        "of those fields does not establish forecast accuracy."
    )
    lines.append("")
    lines.append("What is explicitly not claimed:")
    lines.append("")
    for nonclaim in NONCLAIMS:
        lines.append(f"- {nonclaim}")
    lines.append("")

    lines.append("## The artifact under review")
    lines.append("")
    lines.append(
        "Run the review from a checkout. The generator creates the installed "
        "copy and export for you:"
    )
    lines.append("")
    lines.extend([
        "| Context ID in the JSON | What runs |",
        "|---|---|",
        f"| `{CONTEXT_IDS[0]}` | Commands import this checkout's `src/` directory. |",
        f"| `{CONTEXT_IDS[1]}` | `scripts/package_install_smoke.py` creates a virtual environment, installs the package, and runs its console commands with `PYTHONPATH` removed. |",
        f"| `{CONTEXT_IDS[2]}` | `microcosm_core.release_export` creates an export, then the lookup and scenario tests run from that exported tree. |",
        "",
        "The expected values come from the JSON demonstration below. The review also records the size and hash of FIRST_ACTION.md, which explains those values:",
        "",
    ])
    for subject in subjects:
        lines.append(f"- [{subject['ref']}]({subject['ref']}) — {subject['bytes']} bytes")
    lines.append("")
    lines.append("Their SHA-256 digests, in `shasum -a 256` output form:")
    lines.append("")
    lines.append("```")
    for subject in subjects:
        lines.append(f"{subject['sha256']}  {subject['ref']}")
    lines.append("```")
    lines.append("")
    lines.append(
        "If these hashes differ from the files in your checkout, regenerate "
        f"this guide with `{REFRESH_COMMAND}` and review the changes. "
        "The generated packet records file hashes rather than a Git commit "
        "because exports can omit Git history. The JSON version of this "
        f"guide is `{RECEIPT_REL}`; the builder's `--check` command compares "
        "both generated files with a fresh rendering."
    )
    lines.append("")
    lines.append(
        "Plectis has [published GitHub releases](https://github.com/wcook04/plectis/releases). This review packet has no "
        "external signature or attestation. Its legacy field value "
        f"`external_signature_status: {EXTERNAL_SIGNATURE_STATUS}` describes "
        "that unsigned packet; it is not a statement that no GitHub release exists."
    )
    lines.append("")

    lines.append("## Expectation policy")
    lines.append("")
    lines.append(
        "These expected values are read directly from "
        f"`{COMMITTED_DEMO_RECEIPT_REL}` (copied into every proof packet at "
        f"`{EXPECTATION_EVIDENCE_REF}`, with its SHA-256 hash recorded):"
    )
    lines.append("")
    lines.append(f"- Expected owner: `{expectation['expected_owner_organ_id']}`")
    lines.append(f"- Expected first command: `{expectation['expected_command']}`")
    lines.append(
        f"- Expected validator: `{expectation['expected_validator_command']}`"
    )
    lines.append("")
    lines.append(
        "The `checks` object records these conditions. "
        "In the checkout and export, `command_exit_zero` refers to the lookup "
        "command's exit code, not execution of the suggested command. "
        "In `fresh_install`, both `command_exit_zero` and `assay_exit_zero` "
        "use the single exit code from `scripts/package_install_smoke.py`; "
        "installation or another console-command test can make both false. "
        "Read the package-smoke output and stderr listed in the packet's "
        "`commands` records to identify that failure. `command_cold_runnable` tests "
        "the suggested command's prefix; `command_placeholder_free` requires "
        "nonempty text with no `<` placeholder. `committed_demo_byte_fresh` "
        "records the result of `scripts/build_first_action_demo.py --check` "
        "in the checkout and export. That step does not run in the installed "
        "copy, where `demo_check_applicable` is false."
    )
    lines.append("")
    for name in check_names:
        lines.append(f"- `{name}`")
    lines.append("")
    lines.append(
        f"See [{FIRST_ACTION_DOC_REL}]({FIRST_ACTION_DOC_REL}) for examples of the returned fields. "
        "The scenario-test command is `PYTHONPATH=src python3 -m microcosm_core "
        "comprehension-assay --first-action`. In each copy, its recorded "
        "output must satisfy:"
    )
    lines.append("")
    for requirement in ASSAY_REQUIREMENTS:
        lines.append(f"- {requirement}")
    lines.append("")
    lines.append(
        "`cross_context_agreement` records whether the component IDs and "
        "normalized commands match across the three copies. "
        "`expectation_policy` records whether they match the saved "
        "demonstration. Both comparisons must pass: three copies can return "
        "the same values and still differ from that demonstration."
    )
    lines.append("")
    lines.append(
        "The generator compares source hashes and scans saved outputs. It "
        "also controls the subprocess environment and temporary-directory "
        "locations. The operations are:"
    )
    lines.append("")
    for requirement in INTEGRITY_REQUIREMENTS:
        lines.append(f"- {requirement}")
    lines.append("")
    lines.append(
        "`FORBIDDEN_OUTPUT_NEEDLES` and `PROVIDER_ENV_MARKERS` are defined in "
        "[skeptic_flight_recorder.py](src/microcosm_core/skeptic_flight_recorder.py)."
    )
    lines.append("")

    lines.append("## Run the review")
    lines.append("")
    lines.append("```bash")
    lines.append(REVIEW_ALIAS_COMMAND)
    lines.append("```")
    lines.append("")
    lines.append(
        f"`{REVIEW_ALIAS_COMMAND}` first runs `{GENERATE_COMMANDS[0]}` to "
        f"create a new packet. It then runs `{VERIFY_COMMANDS[0]}` to compare "
        "the packet with its saved output files, and prints the Markdown "
        "summary. Verification does not rerun the recorded commands. To "
        f"verify a packet you already have, run `{VERIFY_COMMANDS[0]}` on its own."
    )
    lines.append("")
    lines.append("Without `make`, run these two commands in order:")
    lines.append("")
    lines.append("```bash")
    lines.append(GENERATE_COMMANDS[1])
    lines.append(VERIFY_COMMANDS[1])
    lines.append("```")
    lines.append("")
    lines.append(
        "Generation can take several minutes because it installs the package "
        "in a new virtual environment and builds an export. Temporary install "
        "and export directories are created outside the source root and "
        "removed after their output is copied. Use `--work-root` to choose "
        "another temporary location or `--keep-work` to retain them. A work "
        "root inside the source tree is refused."
    )
    lines.append("")
    lines.append(f"The results are written under `{PROOF_OUT_DIR}/`:")
    lines.append("")
    lines.append(f"- `{PACKET_FILENAME}`: command arguments, exit codes, output-file hashes, comparisons, and the generator's status.")
    lines.append(f"- `{CARD_FILENAME}`: a Markdown summary of the packet.")
    lines.append(f"- `{VERIFICATION_FILENAME}`: the verifier's recomputed hashes, comparisons, and status.")
    lines.append("")
    lines.append(
        "The review passes only when the generator's status is `pass` and "
        "the verifier's status is `packet_valid`. A `packet_valid` result "
        "can describe a correctly recorded failed run; it does not turn a "
        "generator status of `blocked` into a pass. The packet schema is "
        f"`{PACKET_SCHEMA_VERSION}`."
    )
    lines.append("")
    lines.append(
        f"`{PUBLIC_SITE_PARITY_COMMAND}` runs a separate comparison of the "
        "published website and this checkout. Its command is "
        "`PYTHONPATH=src python3 -m microcosm_core public-site-parity`. It reads "
        "the generated `gh-pages` files and live Pages URL, parses the "
        "downloadable AI handoff packets, recalculates their recorded hashes, "
        "and compares component, family, paper-module and limitation fields "
        "with this source tree. `make release-review` does not run it."
    )
    lines.append("")

    lines.append("## Reading a failure")
    lines.append("")
    lines.append(
        "Start with the generator summary's `blocked_codes` or the verifier's "
        "`statuses`. For a generation failure, open the named context and its "
        "`failed_checks`; use `evidence_refs` to find the saved command output. "
        "For a verification failure, read the matching row in `checks`. "
        "A mismatch identifies what differed; it does not identify who "
        "changed a file or why."
    )
    lines.append("")
    surfaces_in_order: list[str] = []
    for row in FAILURE_INTERPRETATIONS:
        if row["surface"] not in surfaces_in_order:
            surfaces_in_order.append(row["surface"])
    for surface_id in surfaces_in_order:
        lines.append(f"### {_surface_heading(surface_id)}")
        lines.append("")
        for row in FAILURE_INTERPRETATIONS:
            if row["surface"] != surface_id:
                continue
            lines.append(f"**`{row['code']}`**")
            lines.append("")
            lines.append(f"- Means: {row['meaning']}")
            lines.append(f"- Does not mean: {row['does_not_mean']}")
            lines.append("")

    lines.append("## What verification proves — and what it cannot")
    lines.append("")
    lines.append(f"The packet's `proof_boundary` field contains this explanation: {PROOF_BOUNDARY}.")
    lines.append("")
    lines.append(
        "The verifier does not independently observe the original process. "
        "Someone who changes the saved outputs and all corresponding hashes "
        "could construct a consistent packet. Run generation yourself when "
        "you need to know how the commands behave in your environment; "
        "that new run does not authenticate an earlier unsigned record."
    )
    lines.append("")
    md_body = "\n".join(lines)

    receipt = {
        "schema_version": CONTRACT_SCHEMA,
        "generated_by": "scripts/build_release_review.py",
        "refresh_command": REFRESH_COMMAND,
        "doc": DOC_REL,
        "packet_schema_version": PACKET_SCHEMA_VERSION,
        "hero_goal": FIRST_ACTION_HERO_GOAL,
        "contexts": list(CONTEXT_IDS),
        "expectation": expectation,
        "encounter_check_names": check_names,
        "assay_requirements": list(ASSAY_REQUIREMENTS),
        "integrity_requirements": list(INTEGRITY_REQUIREMENTS),
        "artifact_subjects": subjects,
        "commands": {
            "generate": list(GENERATE_COMMANDS),
            "verify": list(VERIFY_COMMANDS),
            "review_alias": REVIEW_ALIAS_COMMAND,
            "public_site_parity": PUBLIC_SITE_PARITY_COMMAND,
            "review_alias_behavior": "generate_fresh_then_verify_then_print_card",
            "no_rerun_verify": VERIFY_COMMANDS[0],
        },
        "outputs": {
            "packet": PACKET_FILENAME,
            "human_card": CARD_FILENAME,
            "verification_receipt": VERIFICATION_FILENAME,
            "out_dir": PROOF_OUT_DIR,
        },
        "pass_criteria": {
            "generate_status": "pass",
            "verify_status": "packet_valid",
        },
        "failure_interpretations": [dict(row) for row in FAILURE_INTERPRETATIONS],
        "proof_boundary": PROOF_BOUNDARY,
        "external_signature_status": EXTERNAL_SIGNATURE_STATUS,
        "publication_binding": "publication_artifact_not_yet_bound",
        "nonclaims": list(NONCLAIMS),
    }
    receipt_body = json.dumps(receipt, ensure_ascii=True, indent=2, sort_keys=True) + "\n"
    return md_body, receipt_body


def _guard_scan(md_body: str, receipt_body: str) -> list[str]:
    """
    Produce the guard scan value used by `scripts.build_release_review`.

    Inputs are `md_body` and `receipt_body`; notable helpers are `search` and `append`.
    """
    tripped: list[str] = []
    joined = md_body + "\n" + receipt_body
    if C._SECRET_SHAPE_RE.search(joined):
        tripped.append("secret_shape")
    if C._PRIVATE_PATH_RE.search(joined):
        tripped.append("private_host_path")
    if any(marker in joined for marker in C._ATOM_BULLET_MARKERS):
        tripped.append("atom_bullet_leak")
    for pattern in PUBLIC_ENTRY_OVERCLAIM_PATTERNS:
        if re.search(pattern, joined, flags=re.IGNORECASE):
            tripped.append(f"overclaim:{pattern}")
    return tripped


def main(argv: list[str] | None = None) -> int:
    """
    Run `scripts.build_release_review` as a command-line entry point.

    The command parses argv, calls this module's builders or validators, and returns the
    status code used by the process wrapper.
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write the contract doc + receipt")
    mode.add_argument("--check", action="store_true", help="exit 1 when committed artifacts drift")
    parser.add_argument(
        "--root", default=None, help="substrate root override (defaults to the package root)"
    )
    args = parser.parse_args(argv)
    root = Path(args.root).resolve() if args.root else C.default_root()

    md_body, receipt_body = build_contract(root)
    tripped = _guard_scan(md_body, receipt_body)
    if tripped:
        print("release review: guard refusal: " + ", ".join(tripped), file=sys.stderr)
        raise SystemExit(3)

    doc_path = root / DOC_REL
    receipt_path = root / RECEIPT_REL
    if args.check:
        drifted = []
        if (
            not doc_path.exists()
            or doc_path.read_text(encoding="utf-8") != md_body + "\n"
        ):
            drifted.append(DOC_REL)
        if (
            not receipt_path.exists()
            or receipt_path.read_text(encoding="utf-8") != receipt_body
        ):
            drifted.append(RECEIPT_REL)
        if drifted:
            print(
                "release review drift: " + ", ".join(drifted) + f"; refresh: {REFRESH_COMMAND}",
                file=sys.stderr,
            )
            return 1
        print("release review: check pass")
        return 0
    receipt_path.parent.mkdir(parents=True, exist_ok=True)
    doc_path.write_text(md_body + "\n", encoding="utf-8")
    receipt_path.write_text(receipt_body, encoding="utf-8")
    print(f"release review: wrote {DOC_REL} and {RECEIPT_REL}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
