"""Generated organ-atlas projection.

Single render path shared by:
- ``scripts/build_organ_atlas.py`` (writes ``ORGANS.md``, ``ARCHITECTURE.md``,
  ``AGENT_ROUTES.md``, and ``atlas/agent_task_routes.json``),
- ``microcosm_core.validators.public_entry_docs`` (drift gate over the written files),
- ``tests/test_organ_atlas.py`` (coverage + honesty contract).

The atlas is a projection, not source authority. Organ identity, evidence
class, claim ceiling, and receipts come from ``core/organ_registry.json``; the
reader-facing grouping comes from ``core/organ_families.json``; the
plain-language glosses come from ``core/organ_atlas.json``. Nothing here
authorizes release, hosting, provider calls, source mutation, private-root
equivalence, or proof authority above each organ's own claim ceiling.
"""

from __future__ import annotations

import json
import re
import shlex
from collections import Counter
from pathlib import Path
from typing import Any

from microcosm_core.projections.concept_mechanism_read_model import (
    build_organ_doctrine_rows,
)
from microcosm_core.projections.organ_surface_contract import (
    build_organ_surface_contract,
)
from microcosm_core.schemas import read_json_strict


REGISTRY_REL = "core/organ_registry.json"
FAMILIES_REL = "core/organ_families.json"
GLOSSES_REL = "core/organ_atlas.json"
EVIDENCE_CLASSES_REL = "core/organ_evidence_classes.json"
SUBSTRATE_LEDGER_REL = "core/substrate_substitution_ledger.json"
PAPER_MODULE_CAPSULES_REL = "core/paper_module_capsules.json"
KERNEL_REL = "core/architecture_kernel.json"
ORGANS_MD_REL = "ORGANS.md"
ARCHITECTURE_MD_REL = "ARCHITECTURE.md"
AGENT_ROUTES_MD_REL = "AGENT_ROUTES.md"
AGENT_TASK_ROUTES_JSON_REL = "atlas/agent_task_routes.json"
SOURCE_MODULE_FILE_GRAPH_REF = "organ-surface-contract::coverage.source_module_file_graph"
ORGAN_TOPOLOGY_SCHEMA = "microcosm_organ_relationship_topology_card_v0"
SOURCE_RELATION_PRIORITY = {
    "source_file.copied_to_public_target": 0,
    "source_file.validated_by_ref": 1,
    "target_file.validated_by_ref": 2,
    "target_file.shares_macro_source_with_target_file": 3,
    "source_shard.retained_as_public_target_shard": 4,
    "source_shard.validated_by_ref": 5,
    "target_shard.validated_by_ref": 6,
}

GENERATED_MARKER = (
    "<!-- GENERATED by scripts/build_organ_atlas.py from core/organ_registry.json, "
    "core/organ_families.json, core/organ_atlas.json, core/organ_evidence_classes.json, "
    "core/substrate_substitution_ledger.json, core/paper_module_capsules.json, "
    "and core/architecture_kernel.json. "
    "Do not hand-edit; "
    "run: PYTHONPATH=src python3 scripts/build_organ_atlas.py --write -->"
)

# Overread guard. Two complementary checks keep cards honest without false
# positives:
#   1. OVERCLAIM_PHRASES are POSITIVE constructions that have no honest use in a
#      card's descriptive fields. Anti-claim NOUNS ("benchmark score",
#      "whole-system correctness", "maturity score", "private-root equivalence")
#      are deliberately NOT here: they appear legitimately inside each card's
#      negated claim ceiling and in organs that *detect* such overclaims.
#   2. Instead, every card's claim ceiling must itself contain a NEGATION_CUE,
#      so each card positively states what it does not authorize.
OVERCLAIM_PHRASES = (
    "release-ready",
    "release ready",
    "production-ready",
    "production ready",
    "ready for production",
    "ready to ship",
    "is private-root equivalent",
    "private-root equivalent to",
    "guarantees correctness",
    "guarantee correctness",
    "proven correct",
    "proves the theorem",
    "state-of-the-art",
    " sota ",
    "outperforms",
    "fully verified",
    "certified secure",
)
NEGATION_CUES = (
    "not",
    "n't",
    " no ",
    "never",
    "without",
    "reject",
    "forbid",
    "cannot",
    "deny",
    "prohibit",
    "exclud",
    "rather than",
    "instead of",
)

CLAIM_CEILING_LINE = (
    "Family labels and counts are navigation metadata, not maturity, completeness, "
    "or release signals. Evidence classes are accounting for what each organ proves, "
    "not scores. Nothing here authorizes release, hosted deployment, provider calls, "
    "source mutation, private-root equivalence, or proof authority above each organ's "
    "own claim ceiling."
)


def _rows(payload: Any, key: str) -> list[dict[str, Any]]:
    if not isinstance(payload, dict):
        return []
    return [row for row in payload.get(key, []) if isinstance(row, dict)]


def _accepted_registry_rows(root: Path) -> list[dict[str, Any]]:
    registry = read_json_strict(root / REGISTRY_REL)
    return [
        row
        for row in _rows(registry, "implemented_organs")
        if row.get("status") == "accepted_current_authority"
    ]


def _paper_module_ref(root: Path, organ_id: str, gloss: dict[str, Any]) -> str | None:
    """Best-effort paper-module path for an organ (used for drilldown links)."""
    declared = str(gloss.get("paper_module_ref") or "").strip()
    if declared:
        if (root / declared).is_file():
            return declared
        declared_path, _, fragment = declared.partition("#")
        if fragment and (root / declared_path).is_file():
            capsule_doc = read_json_strict(root / declared_path)
            for row in _rows(capsule_doc, "paper_modules"):
                if str(row.get("id") or "") != fragment:
                    continue
                projection = str(row.get("legacy_markdown_projection") or "").strip()
                if projection and (root / projection).is_file():
                    return projection
                return declared
        return None
    direct = Path("paper_modules") / f"{organ_id}.md"
    if (root / direct).is_file():
        return direct.as_posix()
    return None


def _paper_module_capsules(root: Path) -> list[dict[str, Any]]:
    path = root / PAPER_MODULE_CAPSULES_REL
    if not path.is_file():
        return []
    payload = read_json_strict(path)
    return _rows(payload, "paper_modules")


def _capsule_index(capsules: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    """Build supported organ/paper-module lookup keys for capsule compression."""
    index: dict[str, dict[str, Any]] = {}
    for row in capsules:
        capsule_id = str(row.get("id") or "").strip()
        legacy_projection = str(row.get("legacy_markdown_projection") or "").strip()
        keys = {
            capsule_id,
            f"{PAPER_MODULE_CAPSULES_REL}#{capsule_id}" if capsule_id else "",
            legacy_projection,
        }
        for subject in row.get("subjects") or []:
            if not isinstance(subject, dict):
                continue
            if subject.get("kind") == "organ" and subject.get("ref"):
                ref = str(subject.get("ref"))
                keys.add(ref)
                keys.add(f"paper_module.{ref}")
        for key in keys:
            if key:
                index.setdefault(key, row)
    return index


def _capsule_for_gloss(
    root: Path,
    organ_id: str,
    gloss: dict[str, Any],
    capsule_by_key: dict[str, dict[str, Any]],
) -> tuple[dict[str, Any] | None, str]:
    declared = str(gloss.get("paper_module_ref") or "").strip()
    lookup_keys: list[str] = []
    if declared:
        lookup_keys.append(declared)
        declared_path, _, fragment = declared.partition("#")
        if fragment:
            lookup_keys.extend([fragment, f"{declared_path}#{fragment}"])
        if declared_path:
            lookup_keys.append(declared_path)
    resolved_module = _paper_module_ref(root, organ_id, gloss)
    if resolved_module:
        lookup_keys.append(resolved_module)
    lookup_keys.extend([f"paper_module.{organ_id}", organ_id])

    seen: set[str] = set()
    for key in lookup_keys:
        if not key or key in seen:
            continue
        seen.add(key)
        row = capsule_by_key.get(key)
        if not row:
            continue
        capsule_id = str(row.get("id") or "")
        status = "direct"
        if capsule_id != f"paper_module.{organ_id}":
            status = "paper_module_ref_bridge"
        return row, status
    return None, "missing"


def _capsule_subject_refs(row: dict[str, Any], kind: str) -> set[str]:
    refs: set[str] = set()
    for subject in row.get("subjects") or []:
        if isinstance(subject, dict) and subject.get("kind") == kind and subject.get("ref"):
            refs.add(str(subject.get("ref")))
    return refs


def _organ_doctrine_by_id(root: Path) -> dict[str, dict[str, Any]]:
    """Projected concept/mechanism rows keyed by accepted organ id."""
    return {
        str(row.get("organ_id")): row
        for row in build_organ_doctrine_rows(root)
        if isinstance(row, dict) and row.get("organ_id")
    }


def _first_n_sorted(values: set[str], limit: int) -> list[str]:
    return sorted(value for value in values if value)[:limit]


def _organ_topology_command(*parts: str) -> str:
    """Render a shell-safe public drilldown command."""
    return " ".join(
        shlex.quote(part) for part in ("microcosm", "organ-topology", *parts)
    )


def _edge_sort_key(edge: dict[str, Any]) -> tuple[int, str, str, str, str]:
    relation_type = str(edge.get("relation_type") or "")
    return (
        SOURCE_RELATION_PRIORITY.get(relation_type, 99),
        str(edge.get("source_ref") or ""),
        str(edge.get("target_ref") or ""),
        str(edge.get("source_shard_ref") or ""),
        str(edge.get("validation_ref") or ""),
    )


def _source_relation_edge_handle(edge: dict[str, Any]) -> dict[str, Any]:
    """Compact, body-free handle for one source-module relation edge."""
    keys = (
        "relation_type",
        "source_ref",
        "target_ref",
        "source_shard_ref",
        "target_shard_ref",
        "required_anchor",
        "validation_ref",
    )
    return {key: edge.get(key) for key in keys if edge.get(key)}


def _source_relation_summary_for_organ(
    organ_id: str,
    edges: list[dict[str, Any]],
) -> dict[str, Any]:
    relation_counts = Counter(
        str(edge.get("relation_type") or "") for edge in edges if edge.get("relation_type")
    )
    source_refs = {
        str(edge.get("source_ref") or "")
        for edge in edges
        if edge.get("source_ref")
    }
    target_refs = {
        str(edge.get("target_ref") or "")
        for edge in edges
        if edge.get("target_ref")
    }
    source_shard_refs = {
        str(edge.get("source_shard_ref") or "")
        for edge in edges
        if edge.get("source_shard_ref")
    }
    target_shard_refs = {
        str(edge.get("target_shard_ref") or "")
        for edge in edges
        if edge.get("target_shard_ref")
    }
    validation_refs = {
        str(edge.get("validation_ref") or "")
        for edge in edges
        if edge.get("validation_ref")
    }
    top_source_refs = _first_n_sorted(source_refs, 5)
    top_target_refs = _first_n_sorted(target_refs, 5)
    top_source_shard_refs = _first_n_sorted(source_shard_refs, 3)
    top_target_shard_refs = _first_n_sorted(target_shard_refs, 3)
    top_validation_refs = _first_n_sorted(validation_refs, 3)

    query_examples = [_organ_topology_command("--organ", organ_id)]
    if top_source_refs:
        query_examples.append(
            _organ_topology_command(
                "--relation-type",
                "file_to_file",
                "--source-ref",
                top_source_refs[0],
            )
        )
    if top_source_shard_refs:
        query_examples.append(
            _organ_topology_command(
                "--relation-type",
                "shard_to_shard",
                "--shard-ref",
                top_source_shard_refs[0],
            )
        )
    if top_validation_refs:
        query_examples.append(
            _organ_topology_command("--validation-ref", top_validation_refs[0])
        )

    return {
        "organ_id": organ_id,
        "source": SOURCE_MODULE_FILE_GRAPH_REF,
        "authority_boundary": (
            "Body-free source-module relation handles only; use organ-topology "
            "for dynamic edge drilldown, not this route row as source authority."
        ),
        "output_schema": ORGAN_TOPOLOGY_SCHEMA,
        "edge_count": len(edges),
        "source_ref_count": len(source_refs),
        "target_ref_count": len(target_refs),
        "source_shard_ref_count": len(source_shard_refs),
        "target_shard_ref_count": len(target_shard_refs),
        "validation_ref_count": len(validation_refs),
        "relation_type_counts": dict(sorted(relation_counts.items())),
        "top_source_refs": top_source_refs,
        "top_target_refs": top_target_refs,
        "top_source_shard_refs": top_source_shard_refs,
        "top_target_shard_refs": top_target_shard_refs,
        "top_validation_refs": top_validation_refs,
        "query_examples": query_examples,
        "example_edges": [
            _source_relation_edge_handle(edge)
            for edge in sorted(edges, key=_edge_sort_key)[:3]
        ],
    }


def _source_relation_summaries_by_organ(root: Path) -> dict[str, dict[str, Any]]:
    """Build compact source-module relation handles keyed by organ id."""
    payload = build_organ_surface_contract(root)
    file_graph = payload["coverage"]["source_module_file_graph"]
    edges_by_organ = file_graph.get("edges_by_organ", {})
    if not isinstance(edges_by_organ, dict):
        return {}
    summaries: dict[str, dict[str, Any]] = {}
    for organ_id, raw_edges in sorted(edges_by_organ.items()):
        edges = [edge for edge in raw_edges if isinstance(edge, dict)]
        if not edges:
            continue
        summaries[str(organ_id)] = _source_relation_summary_for_organ(
            str(organ_id),
            edges,
        )
    return summaries


def _route_source_relation_summary(
    task_class: str,
    organ_summaries: list[dict[str, Any]],
) -> dict[str, Any]:
    relation_counts: Counter[str] = Counter()
    source_refs: set[str] = set()
    target_refs: set[str] = set()
    source_shard_refs: set[str] = set()
    target_shard_refs: set[str] = set()
    validation_refs: set[str] = set()
    source_ref_count = 0
    target_ref_count = 0
    source_shard_ref_count = 0
    target_shard_ref_count = 0
    validation_ref_count = 0
    example_edges: list[dict[str, Any]] = []
    query_examples: list[str] = []

    for summary in organ_summaries:
        relation_counts.update(summary.get("relation_type_counts") or {})
        source_ref_count += int(summary.get("source_ref_count") or 0)
        target_ref_count += int(summary.get("target_ref_count") or 0)
        source_shard_ref_count += int(summary.get("source_shard_ref_count") or 0)
        target_shard_ref_count += int(summary.get("target_shard_ref_count") or 0)
        validation_ref_count += int(summary.get("validation_ref_count") or 0)
        source_refs.update(str(ref) for ref in summary.get("top_source_refs") or [])
        target_refs.update(str(ref) for ref in summary.get("top_target_refs") or [])
        source_shard_refs.update(
            str(ref) for ref in summary.get("top_source_shard_refs") or []
        )
        target_shard_refs.update(
            str(ref) for ref in summary.get("top_target_shard_refs") or []
        )
        validation_refs.update(
            str(ref) for ref in summary.get("top_validation_refs") or []
        )
        example_edges.extend(
            edge for edge in summary.get("example_edges") or [] if isinstance(edge, dict)
        )
        for example in summary.get("query_examples") or []:
            example_text = str(example)
            if example_text and example_text not in query_examples:
                query_examples.append(example_text)

    top_source_refs = _first_n_sorted(source_refs, 5)
    top_source_shard_refs = _first_n_sorted(source_shard_refs, 3)
    top_validation_refs = _first_n_sorted(validation_refs, 3)
    if top_source_refs:
        example = _organ_topology_command(
            "--relation-type",
            "file_to_file",
            "--source-ref",
            top_source_refs[0],
        )
        if example not in query_examples:
            query_examples.append(example)
    if top_source_shard_refs:
        example = _organ_topology_command(
            "--relation-type",
            "shard_to_shard",
            "--shard-ref",
            top_source_shard_refs[0],
        )
        if example not in query_examples:
            query_examples.append(example)
    if top_validation_refs:
        example = _organ_topology_command("--validation-ref", top_validation_refs[0])
        if example not in query_examples:
            query_examples.append(example)

    return {
        "task_class": task_class,
        "source": SOURCE_MODULE_FILE_GRAPH_REF,
        "authority_boundary": (
            "Body-free aggregate over relevant organs; dynamic edge truth remains "
            "in organ-topology."
        ),
        "output_schema": ORGAN_TOPOLOGY_SCHEMA,
        "organ_with_source_relation_count": len(organ_summaries),
        "edge_count": sum(int(summary.get("edge_count") or 0) for summary in organ_summaries),
        "source_ref_count": source_ref_count,
        "target_ref_count": target_ref_count,
        "source_shard_ref_count": source_shard_ref_count,
        "target_shard_ref_count": target_shard_ref_count,
        "validation_ref_count": validation_ref_count,
        "relation_type_counts": dict(sorted(relation_counts.items())),
        "top_source_refs": top_source_refs,
        "top_target_refs": _first_n_sorted(target_refs, 5),
        "top_source_shard_refs": top_source_shard_refs,
        "top_target_shard_refs": _first_n_sorted(target_shard_refs, 3),
        "top_validation_refs": top_validation_refs,
        "query_examples": query_examples[:5],
        "example_edges": example_edges[:5],
    }


def _source_relation_route_handle(
    organ_id: str,
    summary: dict[str, Any] | None,
) -> dict[str, Any] | None:
    """Small per-organ pointer for generated route rows."""
    if not isinstance(summary, dict):
        return None
    query_examples = summary.get("query_examples") or []
    return {
        "source_relation_ref": (
            f"{SOURCE_MODULE_FILE_GRAPH_REF}.edges_by_organ"
            f"[organ_id={organ_id}]"
        ),
        "edge_count": summary.get("edge_count", 0),
        "source_ref_count": summary.get("source_ref_count", 0),
        "target_ref_count": summary.get("target_ref_count", 0),
        "source_shard_ref_count": summary.get("source_shard_ref_count", 0),
        "target_shard_ref_count": summary.get("target_shard_ref_count", 0),
        "validation_ref_count": summary.get("validation_ref_count", 0),
        "query": query_examples[0] if query_examples else "",
    }


def _source_relation_md_line(card: dict[str, Any]) -> str:
    organ_id = str(card["organ_id"])
    summary = card.get("source_relation_summary")
    query = _organ_topology_command("--organ", organ_id)
    if not isinstance(summary, dict):
        return (
            "no source-module file/shard edges recorded in "
            f"`{SOURCE_MODULE_FILE_GRAPH_REF}` · drilldown `{query}`"
        )

    query_examples = [str(example) for example in summary.get("query_examples") or []]
    if query_examples:
        query = query_examples[0]
    source_ref = (
        f"{SOURCE_MODULE_FILE_GRAPH_REF}.edges_by_organ[organ_id={organ_id}]"
    )
    bits = [
        f"`{int(summary.get('edge_count') or 0)}` source-module edges",
        f"`{int(summary.get('source_ref_count') or 0)}` source files",
        f"`{int(summary.get('source_shard_ref_count') or 0)}` source shards",
        f"`{int(summary.get('target_ref_count') or 0)}` target files",
        f"`{int(summary.get('target_shard_ref_count') or 0)}` target shards",
        f"handle `{_md_cell(source_ref)}`",
        f"drilldown `{_md_cell(query)}`",
    ]
    return " · ".join(bits)


def _architecture_source_relation_summary(model: dict[str, Any]) -> dict[str, Any]:
    """Aggregate body-free source relation handles across all accepted organs."""
    summaries = [
        summary
        for family in model.get("families", [])
        for card in family.get("cards", [])
        for summary in [card.get("source_relation_summary")]
        if isinstance(summary, dict)
    ]
    return _route_source_relation_summary("architecture", summaries)


def _architecture_source_relation_commands(summary: dict[str, Any]) -> list[str]:
    """Pick stable architecture drilldowns from the aggregate relation summary."""
    commands: list[str] = []
    for example in summary.get("query_examples") or []:
        command = str(example)
        if command and command not in commands:
            commands.append(command)

    top_source_refs = [str(ref) for ref in summary.get("top_source_refs") or []]
    top_source_shard_refs = [
        str(ref) for ref in summary.get("top_source_shard_refs") or []
    ]
    top_validation_refs = [
        str(ref) for ref in summary.get("top_validation_refs") or []
    ]
    candidates = []
    if top_source_refs:
        candidates.append(
            _organ_topology_command(
                "--relation-type",
                "file_to_file",
                "--source-ref",
                top_source_refs[0],
            )
        )
    if top_source_shard_refs:
        candidates.append(
            _organ_topology_command(
                "--relation-type",
                "shard_to_shard",
                "--shard-ref",
                top_source_shard_refs[0],
            )
        )
    if top_validation_refs:
        candidates.append(
            _organ_topology_command("--validation-ref", top_validation_refs[0])
        )

    for command in candidates:
        if command not in commands:
            commands.append(command)
    return commands[:5]


def load_model(root: str | Path) -> dict[str, Any]:
    """Build the merged, validated atlas model from public substrate.

    Returns a dict with ``status`` ("pass"/"blocked"), ``blocking_reasons``,
    the merged ``families`` (each with resolved organ cards), the evidence-class
    legend, the kernel primitives, and coverage counts. Fails closed: any
    registry/family/gloss mismatch or empty gloss field blocks the model.
    """
    root = Path(root)
    registry_rows = _accepted_registry_rows(root)
    registry_by_id = {str(r.get("organ_id")): r for r in registry_rows}
    registry_ids = set(registry_by_id)

    families_doc = read_json_strict(root / FAMILIES_REL)
    families = [f for f in families_doc.get("families", []) if isinstance(f, dict)]

    glosses_doc: dict[str, Any]
    glosses_path = root / GLOSSES_REL
    if glosses_path.is_file():
        glosses_doc = read_json_strict(glosses_path)
    else:
        glosses_doc = {"organs": []}
    gloss_by_id = {
        str(g.get("organ_id")): g
        for g in glosses_doc.get("organs", [])
        if isinstance(g, dict)
    }
    paper_module_capsules = _paper_module_capsules(root)
    capsule_by_key = _capsule_index(paper_module_capsules)

    evidence_doc = read_json_strict(root / EVIDENCE_CLASSES_REL)
    class_profiles = (
        evidence_doc.get("class_profiles", {})
        if isinstance(evidence_doc, dict)
        else {}
    )
    evidence_class_by_organ = {
        str(r.get("organ_id")): str(r.get("evidence_class"))
        for r in _rows(evidence_doc, "organ_evidence_classes")
    }
    substrate_doc: dict[str, Any] = {}
    substrate_path = root / SUBSTRATE_LEDGER_REL
    if substrate_path.is_file():
        substrate_doc = read_json_strict(substrate_path)
    substrate_by_id = {
        str(r.get("organ_id")): r
        for r in _rows(substrate_doc, "organ_substrate_dispositions")
    }
    doctrine_by_id = _organ_doctrine_by_id(root)
    source_relation_by_organ = _source_relation_summaries_by_organ(root)

    kernel_doc = read_json_strict(root / KERNEL_REL)
    kernel_primitives = _rows(kernel_doc, "primitives")

    # --- coverage validation (fail closed) ---
    family_union: list[str] = []
    family_of: dict[str, str] = {}
    duplicate_in_families: list[str] = []
    for fam in families:
        for oid in fam.get("organ_ids", []):
            if oid in family_of:
                duplicate_in_families.append(oid)
            family_of[oid] = str(fam.get("family_id"))
            family_union.append(oid)
    family_set = set(family_union)

    missing_from_families = sorted(registry_ids - family_set)
    extra_in_families = sorted(family_set - registry_ids)
    missing_glosses = sorted(registry_ids - set(gloss_by_id))
    extra_glosses = sorted(set(gloss_by_id) - registry_ids)

    empty_gloss_fields: list[str] = []
    overclaim_cards: list[str] = []
    ceiling_without_negation: list[str] = []
    empty_specialty: list[str] = []
    unresolved_wires_to: list[str] = []
    missing_capsule_compression: list[str] = []
    missing_capsule_one_line: list[str] = []
    missing_capsule_card: list[str] = []
    missing_capsule_authority_ceiling: list[str] = []
    required_gloss_fields = (
        "display_name",
        "human_gloss",
        "agent_gloss",
        "first_command",
        "claim_ceiling_restated",
    )
    for oid, g in gloss_by_id.items():
        if oid not in registry_ids:
            continue
        for field in required_gloss_fields:
            if not str(g.get(field, "")).strip():
                empty_gloss_fields.append(f"{oid}.{field}")
        # positive overclaim: a never-honest construction in the descriptive fields
        described = " ".join(
            str(g.get(f, ""))
            for f in ("display_name", "human_gloss", "agent_gloss", "first_command")
        ).lower()
        if any(phrase in described for phrase in OVERCLAIM_PHRASES):
            overclaim_cards.append(oid)
        # honesty: every card must state a negated claim ceiling
        ceiling = str(g.get("claim_ceiling_restated", "")).lower()
        if ceiling and not any(cue in ceiling for cue in NEGATION_CUES):
            ceiling_without_negation.append(oid)
        # navigation: specialty tags drive the human "find your area" index
        specialty = g.get("specialty")
        if not (isinstance(specialty, list) and specialty):
            empty_specialty.append(oid)
        # edges must resolve to accepted organs (no dangling wires_to)
        wires = g.get("wires_to")
        if isinstance(wires, list):
            for target in wires:
                if target not in registry_ids:
                    unresolved_wires_to.append(f"{oid}->{target}")
        capsule, _join_status = _capsule_for_gloss(root, oid, g, capsule_by_key)
        if not capsule:
            missing_capsule_compression.append(oid)
            missing_capsule_one_line.append(oid)
            missing_capsule_card.append(oid)
            missing_capsule_authority_ceiling.append(oid)
            continue
        compression = (
            capsule.get("compression")
            if isinstance(capsule.get("compression"), dict)
            else {}
        )
        if not str(compression.get("one_line") or "").strip():
            missing_capsule_one_line.append(oid)
        if not str(compression.get("card") or "").strip():
            missing_capsule_card.append(oid)
        if not str(compression.get("authority_ceiling") or "").strip():
            missing_capsule_authority_ceiling.append(oid)

    blocking_reasons: list[str] = []
    if missing_from_families:
        blocking_reasons.append("registry_organs_missing_from_families")
    if extra_in_families:
        blocking_reasons.append("family_organs_not_in_registry")
    if duplicate_in_families:
        blocking_reasons.append("organ_in_multiple_families")
    if missing_glosses:
        blocking_reasons.append("registry_organs_missing_glosses")
    if extra_glosses:
        blocking_reasons.append("gloss_organs_not_in_registry")
    if empty_gloss_fields:
        blocking_reasons.append("empty_gloss_fields")
    if overclaim_cards:
        blocking_reasons.append("overclaim_in_card")
    if ceiling_without_negation:
        blocking_reasons.append("ceiling_without_negation")
    if empty_specialty:
        blocking_reasons.append("empty_specialty")
    if unresolved_wires_to:
        blocking_reasons.append("unresolved_wires_to")
    if missing_capsule_compression:
        blocking_reasons.append("missing_capsule_compression")
    if missing_capsule_one_line:
        blocking_reasons.append("missing_capsule_one_line")
    if missing_capsule_card:
        blocking_reasons.append("missing_capsule_card")
    if missing_capsule_authority_ceiling:
        blocking_reasons.append("missing_capsule_authority_ceiling")

    # --- merge cards per family ---
    merged_families: list[dict[str, Any]] = []
    capsule_join_status_counts: Counter[str] = Counter()
    used_capsule_ids: set[str] = set()
    for fam in families:
        cards: list[dict[str, Any]] = []
        for oid in fam.get("organ_ids", []):
            reg = registry_by_id.get(oid, {})
            gloss = gloss_by_id.get(oid, {})
            capsule, capsule_join_status = _capsule_for_gloss(
                root,
                oid,
                gloss,
                capsule_by_key,
            )
            capsule_join_status_counts.update([capsule_join_status])
            compression = (
                capsule.get("compression")
                if isinstance(capsule, dict)
                and isinstance(capsule.get("compression"), dict)
                else {}
            )
            capsule_id = str(capsule.get("id") or "") if isinstance(capsule, dict) else ""
            if capsule_id:
                used_capsule_ids.add(capsule_id)
            doctrine = doctrine_by_id.get(oid, {})
            substrate = substrate_by_id.get(oid, {})
            surface_refs = (
                doctrine.get("surface_refs")
                if isinstance(doctrine.get("surface_refs"), dict)
                else {}
            )
            standard_ref = str(
                surface_refs.get("standard")
                or f"standards/std_microcosm_{oid}.json"
            )
            concept_ref = (
                f"organ_doctrine_row:{oid}.concept_binding"
                if doctrine.get("concept_binding")
                else ""
            )
            mechanism_ref = (
                f"organ_doctrine_row:{oid}.mechanism_binding"
                if doctrine.get("mechanism_binding")
                else ""
            )
            acceptance_ref = str(
                surface_refs.get("acceptance")
                or reg.get("current_authority_receipt")
                or ""
            )
            cards.append(
                {
                    "organ_id": oid,
                    "family": str(fam.get("family_id")),
                    "evidence_class": reg.get("evidence_class")
                    or evidence_class_by_organ.get(oid),
                    "evidence_strength_rank": reg.get("evidence_strength_rank"),
                    "claim_ceiling": reg.get("claim_ceiling"),
                    "substrate_disposition": substrate.get("disposition"),
                    "substrate_fixture_role": substrate.get("fixture_role"),
                    "substrate_real_body_count": substrate.get("real_body_count"),
                    "substrate_receipt_body_count": substrate.get("receipt_body_count"),
                    "substrate_claim_ceiling": substrate.get("claim_ceiling"),
                    "substrate_next_repair": substrate.get("next_repair"),
                    "validator_command": reg.get("validator_command"),
                    "generated_receipts": reg.get("generated_receipts", []),
                    "human_gloss": gloss.get("human_gloss", ""),
                    "agent_gloss": gloss.get("agent_gloss", ""),
                    "one_line": compression.get("one_line", ""),
                    "compression_card": compression.get("card", ""),
                    "compression_authority_ceiling": compression.get(
                        "authority_ceiling",
                        "",
                    ),
                    "capsule_id": capsule_id,
                    "capsule_join_status": capsule_join_status,
                    "capsule_legacy_markdown_projection": (
                        str(capsule.get("legacy_markdown_projection") or "")
                        if isinstance(capsule, dict)
                        else ""
                    ),
                    "first_command": gloss.get("first_command", ""),
                    "claim_ceiling_restated": gloss.get("claim_ceiling_restated", ""),
                    "standalone_or_wired": gloss.get("standalone_or_wired", ""),
                    "wiring_note": gloss.get("wiring_note", ""),
                    "display_name": gloss.get("display_name", ""),
                    "specialty": gloss.get("specialty", []),
                    "wires_to": gloss.get("wires_to", []),
                    "paper_module": _paper_module_ref(root, oid, gloss),
                    "standard": standard_ref,
                    "concept_projection": concept_ref,
                    "mechanism_projection": mechanism_ref,
                    "acceptance": acceptance_ref,
                    "source_relation_summary": source_relation_by_organ.get(oid),
                }
            )
        merged_families.append(
            {
                "family_id": str(fam.get("family_id")),
                "label": str(fam.get("label")),
                "blurb": str(fam.get("blurb")),
                "organ_count": len(cards),
                "cards": cards,
            }
        )

    capsule_ids = {
        str(row.get("id") or "")
        for row in paper_module_capsules
        if str(row.get("id") or "")
    }
    capsule_rows_with_organ_subject = {
        str(row.get("id") or "")
        for row in paper_module_capsules
        if _capsule_subject_refs(row, "organ")
    }
    mechanism_only_capsules = {
        str(row.get("id") or "")
        for row in paper_module_capsules
        if _capsule_subject_refs(row, "mechanism")
        and not _capsule_subject_refs(row, "organ")
    }
    markdown_paper_count = len(list((root / "paper_modules").glob("*.md")))
    json_paper_count = len(list((root / "paper_modules").glob("*.json")))
    capsule_accounting = {
        "accepted_organ_count": len(registry_ids),
        "paper_module_capsule_count": len(paper_module_capsules),
        "markdown_paper_module_count": markdown_paper_count,
        "json_paper_module_projection_count": json_paper_count,
        "capsule_rows_with_organ_subject_count": len(capsule_rows_with_organ_subject),
        "mechanism_only_capsule_count": len(mechanism_only_capsules),
        "mechanism_only_capsules_used_by_accepted_organs": sorted(
            used_capsule_ids & mechanism_only_capsules
        ),
        "capsule_rows_not_used_by_accepted_organs": sorted(
            capsule_ids - used_capsule_ids
        ),
        "count_boundary": (
            "Accepted organs, JSON paper-module capsules, and Markdown/JSON paper "
            "module projections are distinct surfaces. A count mismatch is expected "
            "when capsules describe mechanism-only or ahead-of-registry rows, or when "
            "Markdown/JSON projections exist outside the accepted-organ registry."
        ),
    }

    return {
        "status": "pass" if not blocking_reasons else "blocked",
        "blocking_reasons": blocking_reasons,
        "coverage": {
            "registry_organ_count": len(registry_ids),
            "family_count": len(families),
            "gloss_count": len(gloss_by_id),
            "missing_from_families": missing_from_families,
            "extra_in_families": extra_in_families,
            "missing_glosses": missing_glosses,
            "extra_glosses": extra_glosses,
            "empty_gloss_fields": sorted(empty_gloss_fields),
            "overclaim_cards": sorted(overclaim_cards),
            "ceiling_without_negation": sorted(ceiling_without_negation),
            "empty_specialty": sorted(empty_specialty),
            "unresolved_wires_to": sorted(unresolved_wires_to),
            "missing_capsule_compression": sorted(missing_capsule_compression),
            "missing_capsule_one_line": sorted(missing_capsule_one_line),
            "missing_capsule_card": sorted(missing_capsule_card),
            "missing_capsule_authority_ceiling": sorted(
                missing_capsule_authority_ceiling
            ),
            "capsule_join_status_counts": dict(sorted(capsule_join_status_counts.items())),
            "glosses_present": glosses_path.is_file(),
        },
        "capsule_accounting": capsule_accounting,
        "families": merged_families,
        "class_profiles": class_profiles,
        "substrate_summary": substrate_doc.get("summary", {})
        if isinstance(substrate_doc, dict)
        else {},
        "source_relation_summary": {
            "source": SOURCE_MODULE_FILE_GRAPH_REF,
            "output_schema": ORGAN_TOPOLOGY_SCHEMA,
            "organ_count": len(source_relation_by_organ),
            "authority_boundary": (
                "Generated atlas route rows consume compact source-module "
                "relation handles; organ-topology remains dynamic edge authority."
            ),
        },
        "kernel_primitives": kernel_primitives,
        "family_index": families_doc,
    }


def _anchor(label: str) -> str:
    """GitHub-flavored heading anchor: lowercase, drop punctuation, spaces -> hyphens."""
    slug = re.sub(r"[^a-z0-9 -]", "", label.lower())
    return slug.replace(" ", "-")


def _strength_bar(rank: Any) -> str:
    try:
        n = int(rank)
    except (TypeError, ValueError):
        return "?"
    return f"{n}/5"


def _one_line(value: Any) -> str:
    return " ".join(str(value or "").split())


def _md_cell(value: Any) -> str:
    return _one_line(value).replace("|", "\\|")


def _md_link_label(value: Any) -> str:
    return _one_line(value).replace("[", "\\[").replace("]", "\\]")


def _organ_anchor(card: dict[str, Any]) -> str:
    title = str(card.get("display_name") or card["organ_id"])
    return f"ORGANS.md#{_anchor(title)}"


def _organ_anchor_local(card: dict[str, Any]) -> str:
    title = str(card.get("display_name") or card["organ_id"])
    return f"#{_anchor(title)}"


def _organ_local_link(card: dict[str, Any]) -> str:
    label = card.get("display_name") or card["organ_id"]
    return f"[{_md_link_label(label)}]({_organ_anchor_local(card)})"


def _capsule_accounting_md(model: dict[str, Any]) -> str:
    accounting = model.get("capsule_accounting") or {}
    used_mechanism_only = accounting.get("mechanism_only_capsules_used_by_accepted_organs") or []
    unused_capsules = accounting.get("capsule_rows_not_used_by_accepted_organs") or []
    bits = [
        f"`{accounting.get('accepted_organ_count')}` accepted organs",
        f"`{accounting.get('paper_module_capsule_count')}` JSON paper-module capsules",
        f"`{accounting.get('markdown_paper_module_count')}` Markdown paper modules",
        f"`{accounting.get('json_paper_module_projection_count')}` JSON paper-module projections",
    ]
    detail = (
        f"{' · '.join(bits)}. These counts are not expected to match: "
        f"`{accounting.get('mechanism_only_capsule_count')}` capsules are mechanism-only, "
        f"`{len(used_mechanism_only)}` mechanism-only capsules are used by accepted organs "
        "through explicit paper-module references, and "
        f"`{len(unused_capsules)}` capsule rows are not accepted-organ atlas rows."
    )
    boundary = str(accounting.get("count_boundary") or "").strip()
    if boundary:
        detail = f"{detail} {boundary}"
    return detail


def _organ_glance_row(card: dict[str, Any], family_label: str) -> dict[str, Any]:
    authority_ceiling = card.get("compression_authority_ceiling") or ""
    drilldown_target = _organ_anchor(card)
    return {
        "organ_id": card["organ_id"],
        "display_name": card.get("display_name") or card["organ_id"],
        "family": card.get("family"),
        "family_label": family_label,
        "one_line": card.get("one_line") or "",
        "card": card.get("compression_card") or "",
        "authority_ceiling": authority_ceiling,
        "authority_boundary": authority_ceiling,
        "claim_ceiling_restated": authority_ceiling,
        "evidence_class": card.get("evidence_class"),
        "first_command": card.get("first_command"),
        "paper_module_ref": card.get("paper_module"),
        "capsule_id": card.get("capsule_id"),
        "capsule_join_status": card.get("capsule_join_status"),
        "card_ref": drilldown_target,
        "drilldown_target": drilldown_target,
    }


def _organ_glance_ladder(model: dict[str, Any]) -> list[dict[str, Any]]:
    families: list[dict[str, Any]] = []
    for fam in model.get("families", []):
        family_label = str(fam.get("label") or fam.get("family_id") or "")
        families.append(
            {
                "family_id": fam.get("family_id"),
                "label": family_label,
                "organ_count": fam.get("organ_count"),
                "organs": [
                    _organ_glance_row(card, family_label)
                    for card in fam.get("cards", [])
                ],
            }
        )
    return families


def _primary_route_card(cards: list[dict[str, Any]]) -> dict[str, Any]:
    """Pick the atlas-ordered first command for a task class.

    The family/atlas order is already curated. Do not silently re-rank routes
    by evidence strength; the task row remains a selector, not a maturity score.
    """
    return cards[0]


def render_agent_task_routes_json(model: dict[str, Any]) -> dict[str, Any]:
    """Build the generated agent task-route read model from atlas cards."""
    by_task: dict[str, list[dict[str, Any]]] = {}
    for fam in model["families"]:
        for card in fam["cards"]:
            for task_class in card.get("specialty") or []:
                by_task.setdefault(str(task_class), []).append(card)

    routes: list[dict[str, Any]] = []
    for task_class in sorted(by_task):
        cards = by_task[task_class]
        primary = _primary_route_card(cards)
        primary_receipts = [
            str(ref)
            for ref in primary.get("generated_receipts", [])
            if str(ref).strip()
        ]
        receipt_ref = str(primary.get("acceptance") or "").strip()
        if not receipt_ref and primary_receipts:
            receipt_ref = primary_receipts[0]
        relevant_organs = []
        for card in cards:
            receipts = [
                str(ref)
                for ref in card.get("generated_receipts", [])
                if str(ref).strip()
            ]
            organ_source_summary = card.get("source_relation_summary")
            relevant_organs.append(
                {
                    "organ_id": card["organ_id"],
                    "display_name": card.get("display_name") or card["organ_id"],
                    "family": card.get("family"),
                    "evidence_class": card.get("evidence_class"),
                    "evidence_strength_rank": card.get("evidence_strength_rank"),
                    "one_line": card.get("one_line"),
                    "compression_card": card.get("compression_card"),
                    "compression_authority_ceiling": card.get(
                        "compression_authority_ceiling"
                    ),
                    "capsule_id": card.get("capsule_id"),
                    "capsule_join_status": card.get("capsule_join_status"),
                    "first_command": card.get("first_command"),
                    "claim_ceiling": card.get("claim_ceiling_restated"),
                    "receipt_refs": receipts,
                    "acceptance_ref": card.get("acceptance"),
                    "standard_ref": card.get("standard"),
                    "paper_module_ref": card.get("paper_module"),
                    "concept_ref": card.get("concept_projection"),
                    "mechanism_ref": card.get("mechanism_projection"),
                    "drilldown_target": _organ_anchor(card),
                    "wires_to": card.get("wires_to") or [],
                    "source_relation_handle": _source_relation_route_handle(
                        str(card["organ_id"]),
                        organ_source_summary
                        if isinstance(organ_source_summary, dict)
                        else None,
                    ),
                }
            )
        source_relation_summaries = [
            card["source_relation_summary"]
            for card in cards
            if isinstance(card.get("source_relation_summary"), dict)
        ]
        routes.append(
            {
                "task_class": task_class,
                "route_role": "agent_task_class_to_organ_selector",
                "organ_count": len(cards),
                "primary_organ_id": primary["organ_id"],
                "primary_display_name": primary.get("display_name")
                or primary["organ_id"],
                "relevant_organs": relevant_organs,
                "first_command": primary.get("first_command"),
                "allowed_authority": primary.get("claim_ceiling_restated"),
                "evidence_ref": (
                    f"core/organ_registry.json::implemented_organs"
                    f"[organ_id={primary['organ_id']}]"
                ),
                "receipt_ref": receipt_ref,
                "source_relation_summary": _route_source_relation_summary(
                    task_class,
                    source_relation_summaries,
                ),
                "stop_condition": (
                    "Stop when the first command or named receipt is visible, "
                    "the selected organ card is opened, and the card's claim "
                    "ceiling is named before any broader conclusion."
                ),
                "drilldown_target": _organ_anchor(primary),
                "authority_boundary": (
                    "Task routing only. This row selects public organs from the "
                    "frozen atlas; it does not authorize release, hosted "
                    "deployment, provider calls, source mutation, private-root "
                    "equivalence, proof correctness, trading advice, or whole-system "
                    "correctness."
                ),
            }
        )

    return {
        "schema_version": "microcosm_agent_task_routes_v1",
        "surface_role": "generated_agent_task_route_projection",
        "source_refs": [
            REGISTRY_REL,
            FAMILIES_REL,
            GLOSSES_REL,
            EVIDENCE_CLASSES_REL,
            PAPER_MODULE_CAPSULES_REL,
            "atlas/entry_packet.json::concept_mechanism_entry_route",
            "core/public_standard_pressure.json",
            SOURCE_MODULE_FILE_GRAPH_REF,
        ],
        "generation": {
            "do_not_hand_edit": (
                "Generated by PYTHONPATH=src python3 scripts/build_organ_atlas.py "
                "--write from the frozen organ atlas model."
            ),
            "source_model": "microcosm_core.projections.organ_atlas.load_model",
            "source_relation_model": (
                "microcosm_core.projections.organ_surface_contract."
                "build_organ_surface_contract"
            ),
        },
        "route_count": len(routes),
        "accepted_organ_count": model["coverage"]["registry_organ_count"],
        "organ_glance_ladder": _organ_glance_ladder(model),
        "capsule_accounting": model.get("capsule_accounting"),
        "source_relation_route_count": sum(
            1
            for route in routes
            if route["source_relation_summary"].get("edge_count", 0) > 0
        ),
        "source_relation_summary": model.get("source_relation_summary"),
        "authority_boundary": (
            "Agent task routes are selectors over accepted public organ cards. "
            "Authority remains on each organ's registry row, generated receipts, "
            "and claim ceiling."
        ),
        "routes": routes,
    }


def render_agent_routes_md(model: dict[str, Any]) -> str:
    route_model = render_agent_task_routes_json(model)
    out: list[str] = []
    out.append("# Microcosm Agent Task Routes")
    out.append("")
    out.append(GENERATED_MARKER)
    out.append("")
    out.append(
        "This is the agent-facing selector over the frozen organ atlas. Start here "
        "when you know the work shape but not the organ id. Human specialty entry "
        "lives in [ORGANS.md#find-your-specialty](ORGANS.md#find-your-specialty); "
        "full organ cards live in [ORGANS.md](ORGANS.md)."
    )
    out.append("")
    out.append(f"> {CLAIM_CEILING_LINE}")
    out.append("")
    out.append("## How to use this table")
    out.append("")
    out.append(
        "Pick the `task_class` that matches the job, run the first command only "
        "inside the listed authority boundary, then open the drilldown card before "
        "making a broader claim. The JSON read model is "
        "[atlas/agent_task_routes.json](atlas/agent_task_routes.json); it keeps "
        "top-level `routes` as an array of rows keyed by `task_class`, with "
        "`standard_ref`, `paper_module_ref`, `concept_ref`, `mechanism_ref`, and "
        "`source_relation_summary` handles for every relevant organ. Use "
        "`microcosm organ-topology` for dynamic file and shard edge drilldown."
    )
    out.append("")
    out.append("## Agent Task Route Table")
    out.append("")
    out.append(
        "| `task_class` | Relevant organ(s) | First command | Source relation handles | Authority / stop condition | Evidence / doctrine / drilldown |"
    )
    out.append("|---|---|---|---|---|---|")
    for route in route_model["routes"]:
        organs = route["relevant_organs"]
        organ_links = [
            f"[{_md_cell(row['display_name'])}]({row['drilldown_target']})"
            for row in organs[:4]
        ]
        if len(organs) > 4:
            organ_links.append(f"+{len(organs) - 4} more in JSON")
        first_command = f"`{_md_cell(route['first_command'])}`"
        source_summary = route.get("source_relation_summary") or {}
        source_bits = [
            f"`{int(source_summary.get('edge_count') or 0)}` edges",
            f"`{int(source_summary.get('source_ref_count') or 0)}` files",
            f"`{int(source_summary.get('source_shard_ref_count') or 0)}` shards",
        ]
        query_examples = source_summary.get("query_examples") or []
        if query_examples:
            source_bits.append(f"`{_md_cell(query_examples[0])}`")
        authority = (
            f"{_md_cell(route['allowed_authority'])} "
            f"Stop: {_md_cell(route['stop_condition'])}"
        )
        evidence_bits = [
            f"`{_md_cell(route['evidence_ref'])}`",
        ]
        if route.get("receipt_ref"):
            evidence_bits.append(f"`{_md_cell(route['receipt_ref'])}`")
        primary_row = organs[0] if organs else {}
        if primary_row.get("concept_ref"):
            evidence_bits.append(f"`{_md_cell(primary_row['concept_ref'])}`")
        if primary_row.get("mechanism_ref"):
            evidence_bits.append(f"`{_md_cell(primary_row['mechanism_ref'])}`")
        evidence_bits.append(f"[primary card]({route['drilldown_target']})")
        out.append(
            "| "
            f"`{_md_cell(route['task_class'])}` | "
            f"{'; '.join(organ_links)} | "
            f"{first_command} | "
            f"{'<br>'.join(source_bits)} | "
            f"{authority} | "
            f"{'<br>'.join(evidence_bits)} |"
        )
    out.append("")
    out.append("---")
    out.append("")
    out.append(
        "Regenerate this file and `atlas/agent_task_routes.json` with "
        "`PYTHONPATH=src python3 scripts/build_organ_atlas.py --write`."
    )
    out.append("")
    return "\n".join(out)


def render_organs_md(model: dict[str, Any]) -> str:
    out: list[str] = []
    out.append("# Microcosm Organ Atlas")
    out.append("")
    out.append(GENERATED_MARKER)
    out.append("")
    out.append(
        "An **organ** is one accepted public runtime surface: a runnable specimen "
        "with a registry row, a claim ceiling, and receipts. This atlas is the "
        "comprehension layer over all "
        f"{model['coverage']['registry_organ_count']} of them — what each one makes "
        "visible, what an agent runs it for, and what it does **not** authorize."
    )
    out.append("")
    out.append(
        "Most organs are **standalone specimens**: they do not call each other. "
        "They bind to one shared spine — the architecture kernel "
        "(`project -> catalog -> pattern -> standard -> route -> work -> event -> "
        "evidence -> explanation -> assimilation`), the evidence-class registry, and "
        "the authority ceiling. A few are **wired** to other named surfaces; each "
        "card says which. See [ARCHITECTURE.md](ARCHITECTURE.md) for the system shape "
        "and [README.md](README.md) for the first run."
    )
    out.append("")
    out.append(f"> {CLAIM_CEILING_LINE}")
    out.append("")
    out.append("## Microcosm at a glance — every organ in one line")
    out.append("")
    out.append(
        "This is the lowest faithful pass over the public substrate: one row per "
        "accepted organ, grouped in canonical family order with Entry & Reveal "
        "first. One-lines and authority ceilings come from "
        f"`{PAPER_MODULE_CAPSULES_REL}::paper_modules[*].compression`; organ "
        "identity and commands come from the accepted registry/atlas model."
    )
    out.append("")
    for fam in model["families"]:
        out.append(f"### {fam['label']} at a glance")
        out.append("")
        for card in fam["cards"]:
            title = card.get("display_name") or card["organ_id"]
            one_line = _md_cell(card.get("one_line") or "")
            command = _md_cell(card.get("first_command") or "")
            authority = _md_cell(
                card.get("compression_authority_ceiling")
                or card.get("claim_ceiling_restated")
                or ""
            )
            paper_module = card.get("paper_module")
            drill = f"[full card]({_organ_anchor_local(card)})"
            if paper_module:
                drill += f" · [paper module]({paper_module})"
            capsule_id = _md_cell(card.get("capsule_id") or "")
            join_status = _md_cell(card.get("capsule_join_status") or "")
            out.append(
                "- "
                f"**{_md_cell(title)}** (`{_md_cell(card['organ_id'])}`) — "
                f"{one_line} "
                f"Evidence `{_md_cell(card.get('evidence_class') or '?')}`; "
                f"first command `{command}`; "
                f"claim ceiling: {authority}; "
                f"drilldown: {drill}; "
                f"provenance `{capsule_id}` (`{join_status}`)."
            )
        out.append("")
    out.append("### Why the counts are honest")
    out.append("")
    out.append(_capsule_accounting_md(model))
    out.append("")
    out.append("### First command")
    out.append("")
    out.append(
        "Run `microcosm tour --card .` for the local first-screen path, then use "
        "[AGENT_ROUTES.md](AGENT_ROUTES.md) for task-class routing or the "
        "family sections below for per-organ cards."
    )
    out.append("")
    out.append("### What this does not authorize")
    out.append("")
    out.append(CLAIM_CEILING_LINE)
    out.append("")
    out.append("## How to read a card")
    out.append("")
    out.append(
        "Each card carries: **What it makes visible** (plain language) · "
        "**For agents** (what to run it for) · **First command** (copyable) · "
        "**Does not authorize** (the claim ceiling) · **Wiring** (standalone or "
        "wired) · **Source relations** (body-free file/shard edge handle) · "
        "**Drill down** (paper module, standard, concept/mechanism row, "
        "validator command, acceptance receipt)."
    )
    out.append("")
    out.append("## Evidence classes")
    out.append("")
    out.append(
        "The evidence class tells you how strong a card's backing is. It is a "
        "claim-boundary legend, not a score."
    )
    out.append("")
    out.append("| Evidence class | Strength | Claim ceiling | Counts as substrate progress |")
    out.append("|---|---|---|---|")
    profiles = model.get("class_profiles", {})
    for class_id in sorted(profiles):
        prof = profiles[class_id]
        rank = _strength_bar(prof.get("evidence_strength_rank"))
        ceiling = str(prof.get("claim_ceiling", "")).replace("|", "\\|")
        counts = "yes" if prof.get("counts_as_real_substrate_progress") else "no (regression/smoke)"
        out.append(f"| `{class_id}` | {rank} | {ceiling} | {counts} |")
    out.append("")
    out.append("## Families")
    out.append("")
    out.append("Jump to a cluster, then open the cards inside it:")
    out.append("")
    for fam in model["families"]:
        anchor = _anchor(fam["label"])
        out.append(
            f"- [{fam['label']}](#{anchor}) "
            f"({fam['organ_count']}) — {fam['blurb']}"
        )
    out.append("")
    # specialty index: let a reader jump to their discipline, not the whole inventory
    by_specialty: dict[str, list[dict[str, Any]]] = {}
    for fam in model["families"]:
        for card in fam["cards"]:
            for tag in card.get("specialty") or []:
                by_specialty.setdefault(tag, []).append(card)
    if by_specialty:
        out.append("## Find your specialty")
        out.append("")
        out.append(
            "Most readers want one area, not all "
            f"{model['coverage']['registry_organ_count']} organs. Pick a specialty, "
            "then open the linked organ cards."
        )
        out.append("")
        for tag in sorted(by_specialty):
            cards = sorted(
                by_specialty[tag],
                key=lambda card: str(card.get("display_name") or card["organ_id"]).lower(),
            )
            names = ", ".join(_organ_local_link(card) for card in cards)
            out.append(f"- **`{tag}`** ({len(by_specialty[tag])}) — {names}")
        out.append("")
    for fam in model["families"]:
        out.append(f"## {fam['label']}")
        out.append("")
        out.append(f"*{fam['blurb']}* ({fam['organ_count']} organs)")
        out.append("")
        for card in fam["cards"]:
            rank = _strength_bar(card.get("evidence_strength_rank"))
            ev = card.get("evidence_class") or "?"
            title = card.get("display_name") or card["organ_id"]
            out.append(f"### {title}")
            out.append("")
            out.append(
                f"`{ev}` · strength {rank} · {fam['label']}"
            )
            out.append("")
            out.append(f"- **Organ id:** `{card['organ_id']}`")
            specialty = card.get("specialty") or []
            if specialty:
                out.append(
                    "- **Specialty:** " + " · ".join(f"`{tag}`" for tag in specialty)
                )
            disposition = card.get("substrate_disposition") or "missing_disposition"
            real_count = card.get("substrate_real_body_count")
            receipt_count = card.get("substrate_receipt_body_count")
            fixture_role = card.get("substrate_fixture_role") or "unknown_fixture_role"
            out.append(
                "- **Substrate disposition:** "
                f"`{disposition}` · real bodies `{real_count}` · "
                f"receipt bodies `{receipt_count}` · fixture role `{fixture_role}`"
            )
            out.append(f"- **What it makes visible:** {card['human_gloss']}")
            out.append(f"- **For agents:** {card['agent_gloss']}")
            out.append(f"- **First command:** `{card['first_command']}`")
            out.append(f"- **Does not authorize:** {card['claim_ceiling_restated']}")
            wiring = card.get("standalone_or_wired") or "standalone_specimen"
            note = card.get("wiring_note") or "binds only to the shared kernel + evidence/authority spine"
            out.append(f"- **Wiring:** {wiring} — {note}")
            out.append(f"- **Source relations:** {_source_relation_md_line(card)}")
            wires_to = card.get("wires_to") or []
            if wires_to:
                out.append(
                    "- **Wires to:** " + ", ".join(f"`{t}`" for t in wires_to)
                )
            drill = []
            if card.get("paper_module"):
                drill.append(f"paper module [`{card['paper_module']}`]({card['paper_module']})")
            if card.get("standard"):
                drill.append(f"standard [`{card['standard']}`]({card['standard']})")
            if card.get("concept_projection"):
                drill.append(f"concept `{card['concept_projection']}`")
            if card.get("mechanism_projection"):
                drill.append(f"mechanism `{card['mechanism_projection']}`")
            if card.get("validator_command"):
                drill.append(f"validator `{card['validator_command']}`")
            if card.get("acceptance"):
                drill.append(f"acceptance `{card['acceptance']}`")
            if drill:
                out.append(f"- **Drill down:** {' · '.join(drill)}")
            out.append("")
    out.append("---")
    out.append("")
    out.append(
        "Regenerate this file from substrate with "
        "`PYTHONPATH=src python3 scripts/build_organ_atlas.py --write`. The build "
        "fails closed if the registry, families, and glosses disagree."
    )
    out.append("")
    return "\n".join(out)


def render_architecture_md(model: dict[str, Any]) -> str:
    out: list[str] = []
    out.append("# Microcosm Architecture at a Glance")
    out.append("")
    out.append(GENERATED_MARKER)
    out.append("")
    out.append(
        "Microcosm is a local, source-open operating substrate for inspecting how a "
        "larger AI-native workflow system thinks, routes, records work, binds "
        "evidence, and limits its own claims. It turns a folder into local "
        "`.microcosm/` state without mutating your source files, calling external "
        "model providers, or claiming release/proof/production authority."
    )
    out.append("")
    out.append(
        "Read this top-down: identity, the local runtime loop, the claim/evidence "
        "loop, then the organ spine. Every box below resolves to a real command, "
        "file, endpoint, or receipt — diagrams here are routing maps, not decoration."
    )
    out.append("")

    out.append("## Level 0 — what it is")
    out.append("")
    out.append("```text")
    out.append("Microcosm is the public, local cross-section of a larger AI-native system.")
    out.append("A cold reader can run and inspect the architecture without receiving private state.")
    out.append("Start: microcosm hello .   Prove local behavior: microcosm tour --card .")
    out.append("```")
    out.append("")

    out.append("## Level 1 — the local runtime loop")
    out.append("")
    out.append(
        "Bring a folder; Microcosm builds project-local state and reads it back as "
        "cards and a local observatory."
    )
    out.append("")
    out.append("```mermaid")
    out.append("flowchart TD")
    out.append('  A[Cold reader or agent] --> B["microcosm hello PROJECT"]')
    out.append('  B --> C["microcosm tour --card PROJECT"]')
    out.append('  C --> D[".microcosm/ state: catalog, patterns, routes,<br/>work_items, events, evidence, graph, explanations"]')
    out.append('  D --> E["selected_route_id"]')
    out.append('  E --> F["microcosm explain PROJECT ROUTE_ID"]')
    out.append('  E --> G["microcosm observe --card PROJECT"]')
    out.append('  G --> G2["microcosm observe PROJECT (event rows)"]')
    out.append('  D --> H["microcosm status --card PROJECT"]')
    out.append('  H --> I["microcosm authority --card / workingness --card"]')
    out.append("```")
    out.append("")

    out.append("## Level 2 — the claim/evidence loop")
    out.append("")
    out.append(
        "Every claim travels with its evidence class, its proof surface, and the "
        "ceiling on what it is allowed to mean. This is the discipline that keeps "
        "counts honest."
    )
    out.append("")
    out.append("```mermaid")
    out.append("flowchart LR")
    out.append('  Claim["Public claim<br/>(route / organ / count)"] --> Class["Evidence class<br/>core/organ_evidence_classes.json"]')
    out.append('  Class --> Proof["Validator / receipt / source ref<br/>core/organ_registry.json"]')
    out.append('  Proof --> Ceiling["Authority ceiling<br/>microcosm authority --card"]')
    out.append('  Ceiling --> Anti["Anti-claim<br/>(what it does NOT authorize)"]')
    out.append('  Anti --> Drill["Drilldown: paper module / fixture / receipt"]')
    out.append("```")
    out.append("")

    source_summary = _architecture_source_relation_summary(model)
    source_commands = _architecture_source_relation_commands(source_summary)
    relation_counts = source_summary.get("relation_type_counts") or {}
    top_relation_bits = [
        f"`{_md_cell(relation)}` `{count}`"
        for relation, count in sorted(
            relation_counts.items(),
            key=lambda item: (-int(item[1]), str(item[0])),
        )[:5]
    ]

    out.append("## Level 3 — source-module file and shard routing")
    out.append("")
    out.append(
        "The source-module file graph is body-free relation metadata from "
        f"`{SOURCE_MODULE_FILE_GRAPH_REF}`. It connects macro source files and "
        "source shards to public target files, target shards, and validation "
        "refs without making this architecture page the edge authority."
    )
    out.append("")
    out.append("| Handle | Count |")
    out.append("|---|---:|")
    out.append(
        "| Accepted organs with source relations | "
        f"{int(source_summary.get('organ_with_source_relation_count') or 0)} |"
    )
    out.append(
        "| Source-module edges | "
        f"{int(source_summary.get('edge_count') or 0)} |"
    )
    out.append(
        "| Source files (per-organ aggregate) | "
        f"{int(source_summary.get('source_ref_count') or 0)} |"
    )
    out.append(
        "| Source shards (per-organ aggregate) | "
        f"{int(source_summary.get('source_shard_ref_count') or 0)} |"
    )
    out.append(
        "| Target files (per-organ aggregate) | "
        f"{int(source_summary.get('target_ref_count') or 0)} |"
    )
    out.append(
        "| Target shards (per-organ aggregate) | "
        f"{int(source_summary.get('target_shard_ref_count') or 0)} |"
    )
    out.append(
        "| Validation refs (per-organ aggregate) | "
        f"{int(source_summary.get('validation_ref_count') or 0)} |"
    )
    out.append("")
    if top_relation_bits:
        out.append("Top relation types: " + " · ".join(top_relation_bits))
        out.append("")
    out.append("Route into the live topology surface:")
    out.append("")
    for command in source_commands:
        out.append(f"- `{_md_cell(command)}`")
    out.append("")
    out.append(
        "Dynamic edge truth remains in `microcosm organ-topology`; this page only "
        "shows aggregate handles so readers can move from file-to-file and "
        "shard-to-shard relations into the owning topology surface."
    )
    out.append("")

    out.append("## Level 3 — the kernel primitives (shared spine)")
    out.append("")
    out.append(
        "Organs do not call each other. They bind to these kernel primitives, "
        "projected into every scanned project as `.microcosm/architecture.json`."
    )
    out.append("")
    out.append("| Primitive | What it does | Run it | Macro analogue |")
    out.append("|---|---|---|---|")
    for prim in model.get("kernel_primitives", []):
        name = prim.get("public_name") or prim.get("primitive_id")
        does = str(prim.get("what_it_does", "")).replace("|", "\\|")
        cmds = prim.get("runtime_commands") or []
        cmd = f"`{cmds[0]}`" if cmds else "—"
        analogue = str(prim.get("macro_analogue", "")).replace("|", "\\|")
        out.append(f"| **{name}** | {does} | {cmd} | {analogue} |")
    out.append("")

    out.append("## Level 3 — the organ spine, grouped into families")
    out.append("")
    out.append(
        "The "
        f"{model['coverage']['registry_organ_count']} accepted organs cluster into "
        f"{model['coverage']['family_count']} families. Open "
        "[ORGANS.md](ORGANS.md) for the full per-organ cards."
    )
    out.append("")
    out.append("```mermaid")
    out.append("flowchart LR")
    out.append('  P[Project folder] --> M[".microcosm local state"]')
    out.append("  M --> K[Architecture kernel primitives]")
    out.append("  K --> R[Routes / work / events / evidence]")
    out.append("  R --> O[Observatory + explain]")
    out.append("  R --> S[Organ spine]")
    for fam in model["families"]:
        fid = fam["family_id"]
        node = "".join(part[:1].upper() for part in fid.split("_"))[:4] or "F"
        out.append(f'  S --> {node}["{fam["label"]} ({fam["organ_count"]})"]')
    out.append("  S --> V[Validators + receipts]")
    out.append("  S --> AC[Authority ceiling]")
    out.append("```")
    out.append("")
    out.append("| Family | Organs | What it helps you do |")
    out.append("|---|---|---|")
    for fam in model["families"]:
        anchor = _anchor(fam["label"])
        blurb = fam["blurb"].replace("|", "\\|")
        out.append(
            f"| [{fam['label']}](ORGANS.md#{anchor}) | {fam['organ_count']} | {blurb} |"
        )
    out.append("")

    out.append("## Level 3 — organ wiring map")
    out.append("")
    out.append(
        "Each family is a cluster. Most organs are standalone specimens, so cluster "
        "membership is the primary relation; arrows show the few explicit "
        "organ-to-organ wires (mostly the formal-math proof chain). Node labels are "
        "organ display names; see [ORGANS.md](ORGANS.md) for the stable ids."
    )
    out.append("")
    out.append("```mermaid")
    out.append("flowchart LR")
    node_id: dict[str, str] = {}
    for i, fam in enumerate(model["families"]):
        for j, card in enumerate(fam["cards"]):
            node_id[card["organ_id"]] = f"o{i}_{j}"
    for i, fam in enumerate(model["families"]):
        fam_label = fam["label"].replace('"', "'")
        out.append(f'  subgraph F{i}["{fam_label} ({fam["organ_count"]})"]')
        for card in fam["cards"]:
            nid = node_id[card["organ_id"]]
            label = (card.get("display_name") or card["organ_id"])
            label = label.replace('"', "'").replace("&", "and")
            out.append(f'    {nid}["{label}"]')
        out.append("  end")
    for fam in model["families"]:
        for card in fam["cards"]:
            src = node_id[card["organ_id"]]
            for target in card.get("wires_to") or []:
                if target in node_id:
                    out.append(f"  {src} --> {node_id[target]}")
    out.append("```")
    out.append("")

    out.append("## Level 4 — import & drift membrane")
    out.append("")
    out.append(
        "Public carries private by default, but only through a membrane: non-secret "
        "macro bodies are copied with digests and omission receipts; projections are "
        "watched for drift; nothing claims source authority or release."
    )
    out.append("")
    out.append("```mermaid")
    out.append("flowchart TD")
    out.append("  Macro[Macro substrate candidate] --> Plan[Projection import plan]")
    out.append("  Plan --> Copy{Non-secret body copyable?}")
    out.append('  Copy -->|yes| Target["Public target + digest + validator"]')
    out.append('  Copy -->|no| Omit["Omission receipt + public metadata"]')
    out.append("  Target --> Receipt[Validation receipt]")
    out.append("  Omit --> Receipt")
    out.append('  Receipt --> Intake["microcosm intake"]')
    out.append('  Intake --> Drift["microcosm drift-control"]')
    out.append('  Drift --> Ceiling["No live repair · no source authority · no release"]')
    out.append("```")
    out.append("")
    out.append(f"> {CLAIM_CEILING_LINE}")
    out.append("")
    out.append("---")
    out.append("")
    out.append(
        "Regenerate from substrate with "
        "`PYTHONPATH=src python3 scripts/build_organ_atlas.py --write`."
    )
    out.append("")
    return "\n".join(out)


def build(root: str | Path, *, write: bool) -> dict[str, Any]:
    """Build the atlas model and optionally write generated atlas surfaces.

    In ``--check`` callers, pass ``write=False`` and compare the returned
    rendered outputs to the on-disk files.
    """
    root = Path(root)
    model = load_model(root)
    organs_md = render_organs_md(model)
    architecture_md = render_architecture_md(model)
    agent_routes_md = render_agent_routes_md(model)
    agent_task_routes = render_agent_task_routes_json(model)
    agent_task_routes_json = (
        json.dumps(agent_task_routes, ensure_ascii=True, indent=2, sort_keys=True)
        + "\n"
    )
    on_disk_organs = (root / ORGANS_MD_REL).read_text(encoding="utf-8") if (root / ORGANS_MD_REL).is_file() else None
    on_disk_arch = (root / ARCHITECTURE_MD_REL).read_text(encoding="utf-8") if (root / ARCHITECTURE_MD_REL).is_file() else None
    on_disk_agent_routes = (root / AGENT_ROUTES_MD_REL).read_text(encoding="utf-8") if (root / AGENT_ROUTES_MD_REL).is_file() else None
    agent_task_routes_path = root / AGENT_TASK_ROUTES_JSON_REL
    on_disk_agent_task_routes = agent_task_routes_path.read_text(encoding="utf-8") if agent_task_routes_path.is_file() else None
    drift = []
    if on_disk_organs is not None and on_disk_organs != organs_md:
        drift.append(ORGANS_MD_REL)
    if on_disk_arch is not None and on_disk_arch != architecture_md:
        drift.append(ARCHITECTURE_MD_REL)
    if on_disk_agent_routes is not None and on_disk_agent_routes != agent_routes_md:
        drift.append(AGENT_ROUTES_MD_REL)
    if (
        on_disk_agent_task_routes is not None
        and on_disk_agent_task_routes != agent_task_routes_json
    ):
        drift.append(AGENT_TASK_ROUTES_JSON_REL)
    wrote: list[str] = []
    if write and model["status"] == "pass":
        (root / ORGANS_MD_REL).write_text(organs_md, encoding="utf-8")
        (root / ARCHITECTURE_MD_REL).write_text(architecture_md, encoding="utf-8")
        (root / AGENT_ROUTES_MD_REL).write_text(agent_routes_md, encoding="utf-8")
        agent_task_routes_path.parent.mkdir(parents=True, exist_ok=True)
        agent_task_routes_path.write_text(agent_task_routes_json, encoding="utf-8")
        wrote = [
            ORGANS_MD_REL,
            ARCHITECTURE_MD_REL,
            AGENT_ROUTES_MD_REL,
            AGENT_TASK_ROUTES_JSON_REL,
        ]
        drift = []
    return {
        "status": model["status"],
        "blocking_reasons": model["blocking_reasons"],
        "coverage": model["coverage"],
        "drift": drift,
        "wrote": wrote,
        "organs_md": organs_md,
        "architecture_md": architecture_md,
        "agent_routes_md": agent_routes_md,
        "agent_task_routes": agent_task_routes,
        "agent_task_routes_json": agent_task_routes_json,
    }
