"""Generated organ-atlas projection.

Single render path shared by:
- ``scripts/build_organ_atlas.py`` (writes ``ORGANS.md`` and ``ARCHITECTURE.md``),
- ``microcosm_core.validators.public_entry_docs`` (drift gate over the written files),
- ``tests/test_organ_atlas.py`` (coverage + honesty contract).

The atlas is a projection, not source authority. Organ identity, evidence
class, claim ceiling, and receipts come from ``core/organ_registry.json``; the
reader-facing grouping comes from ``core/organ_families.json``; the
plain-language glosses come from ``core/organ_atlas.json``. Nothing here
authorizes release, hosting, provider calls, source mutation, private-root
equivalence, or proof authority above each organ's own claim ceiling.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from microcosm_core.schemas import read_json_strict


REGISTRY_REL = "core/organ_registry.json"
FAMILIES_REL = "core/organ_families.json"
GLOSSES_REL = "core/organ_atlas.json"
EVIDENCE_CLASSES_REL = "core/organ_evidence_classes.json"
KERNEL_REL = "core/architecture_kernel.json"
ORGANS_MD_REL = "ORGANS.md"
ARCHITECTURE_MD_REL = "ARCHITECTURE.md"

GENERATED_MARKER = (
    "<!-- GENERATED by scripts/build_organ_atlas.py from core/organ_registry.json, "
    "core/organ_families.json, core/organ_atlas.json, core/organ_evidence_classes.json, "
    "and core/architecture_kernel.json. Do not hand-edit; "
    "run: PYTHONPATH=src python3 scripts/build_organ_atlas.py --write -->"
)

# Overread guard. Two complementary checks keep cards honest without false
# positives:
#   1. OVERCLAIM_PHRASES are POSITIVE constructions that have no honest use in a
#      card's descriptive fields. Anti-claim NOUNS ("benchmark score",
#      "whole-system correctness", "maturity score", "private-root equivalence")
#      are deliberately NOT here: they appear legitimately inside each card's
#      negated claim ceiling and in organs that *detect* such overclaims.
#   2. Instead, every card's claim ceiling must itself contain a NEGATION_CUE,
#      so each card positively states what it does not authorize.
OVERCLAIM_PHRASES = (
    "release-ready",
    "release ready",
    "production-ready",
    "production ready",
    "ready for production",
    "ready to ship",
    "is private-root equivalent",
    "private-root equivalent to",
    "guarantees correctness",
    "guarantee correctness",
    "proven correct",
    "proves the theorem",
    "state-of-the-art",
    " sota ",
    "outperforms",
    "fully verified",
    "certified secure",
)
NEGATION_CUES = (
    "not",
    "n't",
    " no ",
    "never",
    "without",
    "reject",
    "forbid",
    "cannot",
    "deny",
    "prohibit",
    "exclud",
    "rather than",
    "instead of",
)

CLAIM_CEILING_LINE = (
    "Family labels and counts are navigation metadata, not maturity, completeness, "
    "or release signals. Evidence classes are accounting for what each organ proves, "
    "not scores. Nothing here authorizes release, hosted deployment, provider calls, "
    "source mutation, private-root equivalence, or proof authority above each organ's "
    "own claim ceiling."
)


def _rows(payload: Any, key: str) -> list[dict[str, Any]]:
    if not isinstance(payload, dict):
        return []
    return [row for row in payload.get(key, []) if isinstance(row, dict)]


def _accepted_registry_rows(root: Path) -> list[dict[str, Any]]:
    registry = read_json_strict(root / REGISTRY_REL)
    return [
        row
        for row in _rows(registry, "implemented_organs")
        if row.get("status") == "accepted_current_authority"
    ]


def _paper_module_ref(root: Path, organ_id: str) -> str | None:
    """Best-effort paper-module path for an organ (used for drilldown links)."""
    direct = Path("paper_modules") / f"{organ_id}.md"
    if (root / direct).is_file():
        return direct.as_posix()
    # A handful of paper modules use a shortened filename.
    overrides = {
        "corpus_readiness_mathlib_absence_gate": "paper_modules/corpus_readiness_mathlib_absence.md",
        "mathematical_strategy_atlas_hypothesis_scorer": "paper_modules/mathematical_strategy_atlas.md",
        "tactic_portfolio_availability_probe": "paper_modules/tactic_portfolio_availability.md",
        "target_shape_tactic_routing_gate": "paper_modules/target_shape_tactic_routing.md",
        "undeclared_library_prior_symbol_classifier": "paper_modules/undeclared_library_prior_classifier.md",
        "ring2_premise_retrieval_precision_recall_harness": "paper_modules/ring2_premise_precision_recall.md",
        "provider_context_recipe_budget_policy": "paper_modules/provider_context_recipe_budget.md",
    }
    candidate = overrides.get(organ_id)
    if candidate and (root / candidate).is_file():
        return candidate
    return None


def load_model(root: str | Path) -> dict[str, Any]:
    """Build the merged, validated atlas model from public substrate.

    Returns a dict with ``status`` ("pass"/"blocked"), ``blocking_reasons``,
    the merged ``families`` (each with resolved organ cards), the evidence-class
    legend, the kernel primitives, and coverage counts. Fails closed: any
    registry/family/gloss mismatch or empty gloss field blocks the model.
    """
    root = Path(root)
    registry_rows = _accepted_registry_rows(root)
    registry_by_id = {str(r.get("organ_id")): r for r in registry_rows}
    registry_ids = set(registry_by_id)

    families_doc = read_json_strict(root / FAMILIES_REL)
    families = [f for f in families_doc.get("families", []) if isinstance(f, dict)]

    glosses_doc: dict[str, Any]
    glosses_path = root / GLOSSES_REL
    if glosses_path.is_file():
        glosses_doc = read_json_strict(glosses_path)
    else:
        glosses_doc = {"organs": []}
    gloss_by_id = {
        str(g.get("organ_id")): g
        for g in glosses_doc.get("organs", [])
        if isinstance(g, dict)
    }

    evidence_doc = read_json_strict(root / EVIDENCE_CLASSES_REL)
    class_profiles = (
        evidence_doc.get("class_profiles", {})
        if isinstance(evidence_doc, dict)
        else {}
    )
    evidence_class_by_organ = {
        str(r.get("organ_id")): str(r.get("evidence_class"))
        for r in _rows(evidence_doc, "organ_evidence_classes")
    }

    kernel_doc = read_json_strict(root / KERNEL_REL)
    kernel_primitives = _rows(kernel_doc, "primitives")

    # --- coverage validation (fail closed) ---
    family_union: list[str] = []
    family_of: dict[str, str] = {}
    duplicate_in_families: list[str] = []
    for fam in families:
        for oid in fam.get("organ_ids", []):
            if oid in family_of:
                duplicate_in_families.append(oid)
            family_of[oid] = str(fam.get("family_id"))
            family_union.append(oid)
    family_set = set(family_union)

    missing_from_families = sorted(registry_ids - family_set)
    extra_in_families = sorted(family_set - registry_ids)
    missing_glosses = sorted(registry_ids - set(gloss_by_id))
    extra_glosses = sorted(set(gloss_by_id) - registry_ids)

    empty_gloss_fields: list[str] = []
    overclaim_cards: list[str] = []
    ceiling_without_negation: list[str] = []
    required_gloss_fields = (
        "human_gloss",
        "agent_gloss",
        "first_command",
        "claim_ceiling_restated",
    )
    for oid, g in gloss_by_id.items():
        if oid not in registry_ids:
            continue
        for field in required_gloss_fields:
            if not str(g.get(field, "")).strip():
                empty_gloss_fields.append(f"{oid}.{field}")
        # positive overclaim: a never-honest construction in the descriptive fields
        described = " ".join(
            str(g.get(f, "")) for f in ("human_gloss", "agent_gloss", "first_command")
        ).lower()
        if any(phrase in described for phrase in OVERCLAIM_PHRASES):
            overclaim_cards.append(oid)
        # honesty: every card must state a negated claim ceiling
        ceiling = str(g.get("claim_ceiling_restated", "")).lower()
        if ceiling and not any(cue in ceiling for cue in NEGATION_CUES):
            ceiling_without_negation.append(oid)

    blocking_reasons: list[str] = []
    if missing_from_families:
        blocking_reasons.append("registry_organs_missing_from_families")
    if extra_in_families:
        blocking_reasons.append("family_organs_not_in_registry")
    if duplicate_in_families:
        blocking_reasons.append("organ_in_multiple_families")
    if missing_glosses:
        blocking_reasons.append("registry_organs_missing_glosses")
    if extra_glosses:
        blocking_reasons.append("gloss_organs_not_in_registry")
    if empty_gloss_fields:
        blocking_reasons.append("empty_gloss_fields")
    if overclaim_cards:
        blocking_reasons.append("overclaim_in_card")
    if ceiling_without_negation:
        blocking_reasons.append("ceiling_without_negation")

    # --- merge cards per family ---
    merged_families: list[dict[str, Any]] = []
    for fam in families:
        cards: list[dict[str, Any]] = []
        for oid in fam.get("organ_ids", []):
            reg = registry_by_id.get(oid, {})
            gloss = gloss_by_id.get(oid, {})
            cards.append(
                {
                    "organ_id": oid,
                    "family": str(fam.get("family_id")),
                    "evidence_class": reg.get("evidence_class")
                    or evidence_class_by_organ.get(oid),
                    "evidence_strength_rank": reg.get("evidence_strength_rank"),
                    "claim_ceiling": reg.get("claim_ceiling"),
                    "validator_command": reg.get("validator_command"),
                    "generated_receipts": reg.get("generated_receipts", []),
                    "human_gloss": gloss.get("human_gloss", ""),
                    "agent_gloss": gloss.get("agent_gloss", ""),
                    "first_command": gloss.get("first_command", ""),
                    "claim_ceiling_restated": gloss.get("claim_ceiling_restated", ""),
                    "standalone_or_wired": gloss.get("standalone_or_wired", ""),
                    "wiring_note": gloss.get("wiring_note", ""),
                    "paper_module": _paper_module_ref(root, oid),
                }
            )
        merged_families.append(
            {
                "family_id": str(fam.get("family_id")),
                "label": str(fam.get("label")),
                "blurb": str(fam.get("blurb")),
                "organ_count": len(cards),
                "cards": cards,
            }
        )

    return {
        "status": "pass" if not blocking_reasons else "blocked",
        "blocking_reasons": blocking_reasons,
        "coverage": {
            "registry_organ_count": len(registry_ids),
            "family_count": len(families),
            "gloss_count": len(gloss_by_id),
            "missing_from_families": missing_from_families,
            "extra_in_families": extra_in_families,
            "missing_glosses": missing_glosses,
            "extra_glosses": extra_glosses,
            "empty_gloss_fields": sorted(empty_gloss_fields),
            "overclaim_cards": sorted(overclaim_cards),
            "ceiling_without_negation": sorted(ceiling_without_negation),
            "glosses_present": glosses_path.is_file(),
        },
        "families": merged_families,
        "class_profiles": class_profiles,
        "kernel_primitives": kernel_primitives,
        "family_index": families_doc,
    }


def _anchor(label: str) -> str:
    """GitHub-flavored heading anchor: lowercase, drop punctuation, spaces -> hyphens."""
    slug = re.sub(r"[^a-z0-9 -]", "", label.lower())
    return slug.replace(" ", "-")


def _strength_bar(rank: Any) -> str:
    try:
        n = int(rank)
    except (TypeError, ValueError):
        return "?"
    return f"{n}/5"


def render_organs_md(model: dict[str, Any]) -> str:
    out: list[str] = []
    out.append("# Microcosm Organ Atlas")
    out.append("")
    out.append(GENERATED_MARKER)
    out.append("")
    out.append(
        "An **organ** is one accepted public runtime surface: a runnable specimen "
        "with a registry row, a claim ceiling, and receipts. This atlas is the "
        "comprehension layer over all "
        f"{model['coverage']['registry_organ_count']} of them — what each one makes "
        "visible, what an agent runs it for, and what it does **not** authorize."
    )
    out.append("")
    out.append(
        "Most organs are **standalone specimens**: they do not call each other. "
        "They bind to one shared spine — the architecture kernel "
        "(`project -> catalog -> pattern -> standard -> route -> work -> event -> "
        "evidence -> explanation -> assimilation`), the evidence-class registry, and "
        "the authority ceiling. A few are **wired** to other named surfaces; each "
        "card says which. See [ARCHITECTURE.md](ARCHITECTURE.md) for the system shape "
        "and [README.md](README.md) for the first run."
    )
    out.append("")
    out.append(f"> {CLAIM_CEILING_LINE}")
    out.append("")
    out.append("## How to read a card")
    out.append("")
    out.append(
        "Each card carries: **What it makes visible** (plain language) · "
        "**For agents** (what to run it for) · **First command** (copyable) · "
        "**Does not authorize** (the claim ceiling) · **Wiring** (standalone or "
        "wired) · **Drill down** (paper module, validator command, receipt)."
    )
    out.append("")
    out.append("## Evidence classes")
    out.append("")
    out.append(
        "The evidence class tells you how strong a card's backing is. It is a "
        "claim-boundary legend, not a score."
    )
    out.append("")
    out.append("| Evidence class | Strength | Claim ceiling | Counts as substrate progress |")
    out.append("|---|---|---|---|")
    profiles = model.get("class_profiles", {})
    for class_id in sorted(profiles):
        prof = profiles[class_id]
        rank = _strength_bar(prof.get("evidence_strength_rank"))
        ceiling = str(prof.get("claim_ceiling", "")).replace("|", "\\|")
        counts = "yes" if prof.get("counts_as_real_substrate_progress") else "no (regression/smoke)"
        out.append(f"| `{class_id}` | {rank} | {ceiling} | {counts} |")
    out.append("")
    out.append("## Families")
    out.append("")
    out.append("Jump to a cluster, then open the cards inside it:")
    out.append("")
    for fam in model["families"]:
        anchor = _anchor(fam["label"])
        out.append(
            f"- [{fam['label']}](#{anchor}) "
            f"({fam['organ_count']}) — {fam['blurb']}"
        )
    out.append("")
    for fam in model["families"]:
        out.append(f"## {fam['label']}")
        out.append("")
        out.append(f"*{fam['blurb']}* ({fam['organ_count']} organs)")
        out.append("")
        for card in fam["cards"]:
            rank = _strength_bar(card.get("evidence_strength_rank"))
            ev = card.get("evidence_class") or "?"
            out.append(
                f"### `{card['organ_id']}`"
            )
            out.append("")
            out.append(
                f"`{ev}` · strength {rank} · {fam['label']}"
            )
            out.append("")
            out.append(f"- **What it makes visible:** {card['human_gloss']}")
            out.append(f"- **For agents:** {card['agent_gloss']}")
            out.append(f"- **First command:** `{card['first_command']}`")
            out.append(f"- **Does not authorize:** {card['claim_ceiling_restated']}")
            wiring = card.get("standalone_or_wired") or "standalone_specimen"
            note = card.get("wiring_note") or "binds only to the shared kernel + evidence/authority spine"
            out.append(f"- **Wiring:** {wiring} — {note}")
            drill = []
            if card.get("paper_module"):
                drill.append(f"paper module [`{card['paper_module']}`]({card['paper_module']})")
            if card.get("validator_command"):
                drill.append(f"validator `{card['validator_command']}`")
            receipts = card.get("generated_receipts") or []
            if receipts:
                drill.append(f"receipt `{receipts[0]}`")
            if drill:
                out.append(f"- **Drill down:** {' · '.join(drill)}")
            out.append("")
    out.append("---")
    out.append("")
    out.append(
        "Regenerate this file from substrate with "
        "`PYTHONPATH=src python3 scripts/build_organ_atlas.py --write`. The build "
        "fails closed if the registry, families, and glosses disagree."
    )
    out.append("")
    return "\n".join(out)


def render_architecture_md(model: dict[str, Any]) -> str:
    out: list[str] = []
    out.append("# Microcosm Architecture at a Glance")
    out.append("")
    out.append(GENERATED_MARKER)
    out.append("")
    out.append(
        "Microcosm is a local, source-open operating substrate for inspecting how a "
        "larger AI-native workflow system thinks, routes, records work, binds "
        "evidence, and limits its own claims. It turns a folder into local "
        "`.microcosm/` state without mutating your source files, calling external "
        "model providers, or claiming release/proof/production authority."
    )
    out.append("")
    out.append(
        "Read this top-down: identity, the local runtime loop, the claim/evidence "
        "loop, then the organ spine. Every box below resolves to a real command, "
        "file, endpoint, or receipt — diagrams here are routing maps, not decoration."
    )
    out.append("")

    out.append("## Level 0 — what it is")
    out.append("")
    out.append("```text")
    out.append("Microcosm is the public, local cross-section of a larger AI-native system.")
    out.append("A cold reader can run and inspect the architecture without receiving private state.")
    out.append("Start: microcosm hello .   Prove local behavior: microcosm tour --card .")
    out.append("```")
    out.append("")

    out.append("## Level 1 — the local runtime loop")
    out.append("")
    out.append(
        "Bring a folder; Microcosm builds project-local state and reads it back as "
        "cards and a local observatory."
    )
    out.append("")
    out.append("```mermaid")
    out.append("flowchart TD")
    out.append('  A[Cold reader or agent] --> B["microcosm hello PROJECT"]')
    out.append('  B --> C["microcosm tour --card PROJECT"]')
    out.append('  C --> D[".microcosm/ state: catalog, patterns, routes,<br/>work_items, events, evidence, graph, explanations"]')
    out.append('  D --> E["selected_route_id"]')
    out.append('  E --> F["microcosm explain PROJECT ROUTE_ID"]')
    out.append('  E --> G["microcosm observe PROJECT"]')
    out.append('  D --> H["microcosm status --card PROJECT"]')
    out.append('  H --> I["microcosm authority --card / workingness --card"]')
    out.append("```")
    out.append("")

    out.append("## Level 2 — the claim/evidence loop")
    out.append("")
    out.append(
        "Every claim travels with its evidence class, its proof surface, and the "
        "ceiling on what it is allowed to mean. This is the discipline that keeps "
        "counts honest."
    )
    out.append("")
    out.append("```mermaid")
    out.append("flowchart LR")
    out.append('  Claim["Public claim<br/>(route / organ / count)"] --> Class["Evidence class<br/>core/organ_evidence_classes.json"]')
    out.append('  Class --> Proof["Validator / receipt / source ref<br/>core/organ_registry.json"]')
    out.append('  Proof --> Ceiling["Authority ceiling<br/>microcosm authority --card"]')
    out.append('  Ceiling --> Anti["Anti-claim<br/>(what it does NOT authorize)"]')
    out.append('  Anti --> Drill["Drilldown: paper module / fixture / receipt"]')
    out.append("```")
    out.append("")

    out.append("## Level 3 — the kernel primitives (shared spine)")
    out.append("")
    out.append(
        "Organs do not call each other. They bind to these kernel primitives, "
        "projected into every scanned project as `.microcosm/architecture.json`."
    )
    out.append("")
    out.append("| Primitive | What it does | Run it | Macro analogue |")
    out.append("|---|---|---|---|")
    for prim in model.get("kernel_primitives", []):
        name = prim.get("public_name") or prim.get("primitive_id")
        does = str(prim.get("what_it_does", "")).replace("|", "\\|")
        cmds = prim.get("runtime_commands") or []
        cmd = f"`{cmds[0]}`" if cmds else "—"
        analogue = str(prim.get("macro_analogue", "")).replace("|", "\\|")
        out.append(f"| **{name}** | {does} | {cmd} | {analogue} |")
    out.append("")

    out.append("## Level 3 — the organ spine, grouped into families")
    out.append("")
    out.append(
        "The "
        f"{model['coverage']['registry_organ_count']} accepted organs cluster into "
        f"{model['coverage']['family_count']} families. Open "
        "[ORGANS.md](ORGANS.md) for the full per-organ cards."
    )
    out.append("")
    out.append("```mermaid")
    out.append("flowchart LR")
    out.append('  P[Project folder] --> M[".microcosm local state"]')
    out.append("  M --> K[Architecture kernel primitives]")
    out.append("  K --> R[Routes / work / events / evidence]")
    out.append("  R --> O[Observatory + explain]")
    out.append("  R --> S[Organ spine]")
    for fam in model["families"]:
        fid = fam["family_id"]
        node = "".join(part[:1].upper() for part in fid.split("_"))[:4] or "F"
        out.append(f'  S --> {node}["{fam["label"]} ({fam["organ_count"]})"]')
    out.append("  S --> V[Validators + receipts]")
    out.append("  S --> AC[Authority ceiling]")
    out.append("```")
    out.append("")
    out.append("| Family | Organs | What it helps you do |")
    out.append("|---|---|---|")
    for fam in model["families"]:
        anchor = _anchor(fam["label"])
        blurb = fam["blurb"].replace("|", "\\|")
        out.append(
            f"| [{fam['label']}](ORGANS.md#{anchor}) | {fam['organ_count']} | {blurb} |"
        )
    out.append("")

    out.append("## Level 4 — import & drift membrane")
    out.append("")
    out.append(
        "Public carries private by default, but only through a membrane: non-secret "
        "macro bodies are copied with digests and omission receipts; projections are "
        "watched for drift; nothing claims source authority or release."
    )
    out.append("")
    out.append("```mermaid")
    out.append("flowchart TD")
    out.append("  Macro[Macro substrate candidate] --> Plan[Projection import plan]")
    out.append("  Plan --> Copy{Non-secret body copyable?}")
    out.append('  Copy -->|yes| Target["Public target + digest + validator"]')
    out.append('  Copy -->|no| Omit["Omission receipt + public metadata"]')
    out.append("  Target --> Receipt[Validation receipt]")
    out.append("  Omit --> Receipt")
    out.append('  Receipt --> Intake["microcosm intake"]')
    out.append('  Intake --> Drift["microcosm drift-control"]')
    out.append('  Drift --> Ceiling["No live repair · no source authority · no release"]')
    out.append("```")
    out.append("")
    out.append(f"> {CLAIM_CEILING_LINE}")
    out.append("")
    out.append("---")
    out.append("")
    out.append(
        "Regenerate from substrate with "
        "`PYTHONPATH=src python3 scripts/build_organ_atlas.py --write`."
    )
    out.append("")
    return "\n".join(out)


def build(root: str | Path, *, write: bool) -> dict[str, Any]:
    """Build the atlas model and optionally write ORGANS.md/ARCHITECTURE.md.

    In ``--check`` callers, pass ``write=False`` and compare the returned
    ``organs_md``/``architecture_md`` to the on-disk files.
    """
    root = Path(root)
    model = load_model(root)
    organs_md = render_organs_md(model)
    architecture_md = render_architecture_md(model)
    on_disk_organs = (root / ORGANS_MD_REL).read_text(encoding="utf-8") if (root / ORGANS_MD_REL).is_file() else None
    on_disk_arch = (root / ARCHITECTURE_MD_REL).read_text(encoding="utf-8") if (root / ARCHITECTURE_MD_REL).is_file() else None
    drift = []
    if on_disk_organs is not None and on_disk_organs != organs_md:
        drift.append(ORGANS_MD_REL)
    if on_disk_arch is not None and on_disk_arch != architecture_md:
        drift.append(ARCHITECTURE_MD_REL)
    wrote: list[str] = []
    if write and model["status"] == "pass":
        (root / ORGANS_MD_REL).write_text(organs_md, encoding="utf-8")
        (root / ARCHITECTURE_MD_REL).write_text(architecture_md, encoding="utf-8")
        wrote = [ORGANS_MD_REL, ARCHITECTURE_MD_REL]
        drift = []
    return {
        "status": model["status"],
        "blocking_reasons": model["blocking_reasons"],
        "coverage": model["coverage"],
        "drift": drift,
        "wrote": wrote,
        "organs_md": organs_md,
        "architecture_md": architecture_md,
    }
